{
  "hash": "6479a3dd86490b2be4a03f403ace04ab",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5\"\nauthor: \"Jin Jiaying\"\ndate: \"25 Sep 2026\"\ndate-modified: last-modified\n---\n\n# Loading R Packages\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse, sfdep)\n```\n:::\n\n\n# 5.1 Global Measures of Spatial Autocorrelation\n\n## 5.1.1 Getting the Data Into R Environment\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"hands-on_ex5_data\", layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\Users\\jiayi\\Documents\\SMU\\26_Aug_Term\\GAA\\lw0170_GAA\\ISSS626_course\\hands-on_exercise\\hands-on_ex5_data' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"hands-on_ex5_data/Hunan_2012.csv\")\n\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## 5.1.2 Global Measures of Spatial Autocorrelation\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"poly2nb()\"}\npoly2nb() of spdep package is used to compute contiguity weight matrices for the study area, thus to build a neighbours list based on regions with contiguous boundaries.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, \n                   style=\"W\", \n                   zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Style of Row-standardised weights matrix\"}\nStyle can take values “W”, “B”, “C”, “U”, “minmax” and “S”. \n\n- B is the basic binary coding\n\n- W is row standardised (sums over all links to n)\n\n- C is globally standardised (sums over all links to n)\n\n- U is equal to C divided by the number of neighbours (sums over all links to unity)\n\n- S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n).\n:::\n\n## 5.1.3 Global Measures of Spatial Autocorrelation: Moran’s I\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, \n           listw=rswm_q, \n           zero.policy = TRUE, \n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical conclusion can be drawn from the output above?\"}\nThe Moran’s I statistic is 0.30075 with a p-value of 1.095e-06.\n\nSince the p-value is smaller than 0.05, the null hypothesis of spatial randomness is rejected. Therefore, there is statistically significant positive spatial autocorrelation in GDP per capita across Hunan counties, indicating that counties with similar GDPPC values tend to be located near one another.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical conclustion can be drawn from the output above?\"}\nThe Monte Carlo permutation test produces an observed Moran’s I of 0.30075 with a pseudo p-value of 0.001. Since the p-value is below 0.05, the null hypothesis of spatial randomness is rejected. This provides further evidence of statistically significant positive spatial autocorrelation in GDPPC.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical observation can be drawn from the output above?\"}\nThe simulated Moran’s I values are centered around approximately -0.015, which is close to the expected value under spatial randomness. The observed Moran’s I of 0.30075 is substantially higher than the simulated values and lies at the extreme upper tail of the permutation distribution. This provides strong evidence that the observed positive spatial autocorrelation is unlikely to have occurred by chance.\n:::\n\n### Challenge: Instead of using Base Graph to plot the values, plot the values by using ggplot2 package\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(moran_i = bperm$res[1:999]),\n       aes(x = moran_i)) +\n  geom_histogram(bins = 20,\n                 fill = \"lightblue\",\n                 color = \"black\") +\n  geom_vline(\n    xintercept = 0.30075,\n    color = \"red\",\n    linetype = \"dashed\"\n  ) +\n  labs(\n    title = \"Monte Carlo Simulation of Moran's I\",\n    x = \"Simulated Moran's I\",\n    y = \"Frequency\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Interpretation\"}\nMonte Carlo simulation evaluates whether the observed spatial autocorrelation could reasonably occur by chance. The farther the observed Moran’s I lies in the tail of the simulated distribution, the stronger the evidence against spatial randomness.\n:::\n\n## 5.1.4 Global Measures of Spatial Autocorrelation: Geary’s C\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical conclusion can be drawn from the output above?\"}\nThe Geary’s C statistic is 0.69072 with a p-value of 0.0001526. Since Geary’s C is below 1 and the p-value is smaller than 0.05, the null hypothesis of spatial randomness is rejected. Therefore, GDPPC exhibits statistically significant positive spatial autocorrelation, indicating that neighbouring counties tend to have similar GDPPC values.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC, \n               listw=rswm_q, \n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical conclusion can be drawn from the output above?\"}\nThe Monte Carlo Geary’s C test gives an observed statistic of 0.69072 with a pseudo p-value of 0.001. Since the observed value is substantially below 1 and the p-value is below 0.05, the null hypothesis of spatial randomness is rejected. The result confirms significant positive spatial autocorrelation in GDPPC.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n\n```{.r .cell-code}\nhist(bperm$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary c\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical observation can be drawn from the output?\"}\nThe simulated Geary’s C values are centered around 1, which is the expected value under spatial randomness. The observed Geary’s C of 0.69072 lies at the extreme lower tail of the simulated distribution. This indicates that the observed positive spatial autocorrelation is unlikely to have occurred by chance.\n:::\n\n## 5.1.5 Spatial Correlogram\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"I\", \n                          style=\"W\")\nplot(MI_corr)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       2.189e-06 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       2.029e-06 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       5.984e-05 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical observation can be drawn from the output?\"}\nThe Moran’s I correlogram shows significant positive spatial autocorrelation at the first three spatial lags, with the strength of autocorrelation decreasing as lag distance increases. At lag 4, the spatial autocorrelation is no longer statistically significant. At lags 5 and 6, Moran’s I becomes significantly negative. Overall, this suggests that similar GDPPC values tend to cluster at shorter spatial ranges, while this similarity weakens and eventually reverses at higher spatial lags.\nIn short, **spatial autocorrelation is scale-dependent** and **positive autocorrelation dominates at short spatial lags**.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"C\", \n                          style=\"W\")\nplot(GC_corr)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical observation can be drawn from the output?\"}\nThe Geary’s C correlogram shows significant positive spatial autocorrelation at lags 1 and 2. The relationship becomes statistically insignificant at lags 3 and 4. At lag 5, Geary’s C exceeds 1 and is statistically significant, indicating negative spatial autocorrelation. At lag 6, the relationship is no longer statistically significant.\n:::\n\n\n# 5.2 Local Measures of Spatial Autocorrelation\n\n## 5.2.1 Getting the Data Into R Environment\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_transform(hunan, crs = 32650)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"GDPPC\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"GDPPC\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Quantile interval classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Interpretation\"}\nInterpretation\nThe choropleth maps may reveal apparent spatial concentrations of high and low GDPPC values. However, visual inspection alone cannot determine whether these patterns represent statistically significant spatial clusters or outliers.\nTherefore, Local Indicators of Spatial Association (LISA) and Getis-Ord Gi* statistics are required to formally identify significant local spatial patterns.\n:::\n\n## 5.2.2 Local Indicators of Spatial Association(LISA)\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hunan %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(\n           nb, style = \"W\"),\n         .before = 1)\n\nsummary(wm_q$nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nlisa <- wm_q %>% \n  mutate(local_moran = local_moran(\n    GDPPC, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\n\nglimpse(lisa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 21\n$ ii           <dbl> -1.468468e-03, 2.587817e-02, -1.198765e-02, 1.022468e-03,…\n$ eii          <dbl> 1.472724e-03, -1.337157e-02, 2.542108e-03, -9.522978e-05,…\n$ var_ii       <dbl> 5.187992e-04, 1.413972e-02, 1.109689e-01, 4.768012e-06, 1…\n$ z_ii         <dbl> -0.12912898, 0.33007787, -0.04361717, 0.51186518, 0.33919…\n$ p_ii         <dbl> 8.972556e-01, 7.413411e-01, 9.652096e-01, 6.087454e-01, 7…\n$ p_ii_sim     <dbl> 0.80, 0.98, 0.92, 0.56, 0.58, 0.86, 0.06, 0.12, 0.02, 0.2…\n$ p_folded_sim <dbl> 0.40, 0.49, 0.46, 0.28, 0.29, 0.43, 0.03, 0.06, 0.01, 0.1…\n$ skewness     <dbl> -1.0560692, -1.0439328, 0.8429629, 0.8423923, 1.3810032, …\n$ kurtosis     <dbl> 1.31492710, 0.76654076, 0.12251048, 0.37514702, 2.3883407…\n$ mean         <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ median       <fct> High-High, High-High, High-High, High-High, High-High, Hi…\n$ pysal        <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ nb           <nb> <2, 3, 4, 57, 85>, <1, 57, 58, 78, 85>, <1, 4, 5, 85>, <1,…\n$ wt           <list> <0.2, 0.2, 0.2, 0.2, 0.2>, <0.2, 0.2, 0.2, 0.2, 0.2>, <0…\n$ NAME_2       <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"C…\n$ ID_3         <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2…\n$ NAME_3       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ ENGTYPE_3    <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"C…\n$ County       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ GDPPC        <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7…\n$ geometry     <POLYGON [m]> POLYGON ((22320.48 3301894,..., POLYGON ((35522.9…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Moran's I\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Loal Moran's I of GDPPC (Queen's method)\")\n\np_ii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_in(\"left\", \"bottom\")\n    )) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Loal Moran's I of GDPPC (Queen's method)\")\n\ntmap_arrange(ii.map, p_ii.map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(lag_GDPPC = st_lag(\n    GDPPC, nb, wt),\n    .before = 1) %>%\n  unnest(lag_GDPPC)\n```\n:::\n\n\n### 5.2.2a Moran scatterplot\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = GDPPC, \n           y = lag_GDPPC)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"red\") +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n### 5.2.2b Moran Scatterplot with LISA Quadrants\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = GDPPC, \n           y = lag_GDPPC, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$lag_GDPPC), lty=2) + \n    geom_vline(xintercept=mean(lisa$GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n### 5.2.2c Moran scatterplot with standardised variable\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(z_GDPPC = scale(GDPPC),\n         z_lag_GDPPC = scale(lag_GDPPC),\n         .before = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = z_GDPPC, \n           y = z_lag_GDPPC, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$z_lag_GDPPC), lty=2) + \n    geom_vline(xintercept=mean(lisa$z_GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"Standardised GDPPC\",\n       y = \"Standardised Spatial Lag of GDPPC\",\n       title = \"Standardised Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n### 5.2.2d LISA map\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- 0.05\n\nlisa <- lisa %>%\n  mutate(\n    LISA_cluster = ifelse(\n      p_ii < 0.05,\n      as.character(mean), \n      \"Insignificant\"),\n    LISA_cluster = factor(\n      LISA_cluster,\n      levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\")\n    )\n  )\n\nlisa_map <- tm_shape(lisa) + \n  tm_polygons(\n    fill = \"LISA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"blue\",        # Low-Low\n        \"lightblue\",   # Low-High\n        \"pink\",        # High-Low\n        \"red\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"LISA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"Local Moran's I Clusters (p < 0.05)\")\nlisa_map\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical observations can you draw from the LISA map above?\"}\nThe LISA map reveals statistically significant local spatial patterns in GDPPC across Hunan. High–High and Low–Low areas represent positive local spatial autocorrelation, indicating clusters where counties have GDPPC values similar to those of their neighbours.\n\nHigh–Low and Low–High areas represent spatial outliers, where a county's GDPPC differs from the values of its surrounding counties. Areas classified as insignificant do not provide sufficient statistical evidence of local spatial association at the 5% significance level.\n\nTherefore, the LISA analysis shows that the **spatial pattern of GDPPC is heterogeneous**: significant clusters and spatial outliers occur only in particular parts of Hunan rather than uniformly across the province.\n:::\n\n## 5.2.3 Hot Spots and Cold Spots Analysis (HCSA)\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- critical_threshold(st_geometry(hunan))\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 60799.91\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan_fdw <- hunan %>% \n  mutate(nb = include_self(\n    st_dist_band(\n      st_geometry(geometry), \n                 upper = ct)),\n    wt = st_weights(nb, \n                      style = \"W\"),\n    .before = 1) \n\nhunan_adw <- hunan %>%\n  mutate(nb = include_self(\n    st_knn(\n      st_geometry(geometry),\n      k = 6)),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_fdw <- hunan_fdw %>%\n  mutate(\n    gistar = local_gstar_perm(\n      GDPPC, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(gistar)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGi_star_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"gi_star\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"-brewer.rd_bu\"),\n              fill.legend = tm_legend(\n                title = \"local Gi*\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Gi* of GDPPC\")\n\np_values_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"p_sim\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n                values = \"-brewer.reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_in(\"left\", \"bottom\")\n    )) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of local Gi* of GDPPC (fixed distance)\")\n\ntmap_arrange(Gi_star_map, p_values_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_fdw <- HCSA_fdw %>%\n  mutate(HCSA_cluster = case_when(\n    p_sim > 0.05 ~ \"Insignificant\",\n    p_sim <= 0.05 & cluster == \"High\" ~ \"Hot spot\",\n    p_sim <= 0.05 & cluster == \"Low\"  ~ \"Cold spot\",\n    TRUE ~ \"Other\"),\n    HCSA_cluster = factor(\n      HCSA_cluster,\n      levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\")\n    ),\n    .before = 1\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_map <- tm_shape(HCSA_fdw) + \n  tm_polygons(\n    fill = \"HCSA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"red\",        # Low-Low\n        \"blue\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"HSCA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"HCSA Clusters (p < 0.05)\")\nHCSA_map\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_arrange(Gi_star_map, HCSA_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](hands-on_exercise_5_files/figure-html/unnamed-chunk-32-2.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Question: What statistical observations can you draw from the LISA map above?\"}\nThe HCSA map identifies statistically significant concentrations of high and low GDPPC values. Hot spots represent counties where high GDPPC values are surrounded by other high values, while cold spots represent concentrations of low GDPPC values.\nCounties classified as insignificant do not provide sufficient statistical evidence of either a hot spot or a cold spot at the 5% significance level.\nThe results therefore indicate that high and low levels of economic development are spatially concentrated in particular parts of Hunan rather than being uniformly distributed across the province.\n:::\n",
    "supporting": [
      "hands-on_exercise_5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}