<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jin Jiaying">
<meta name="dcterms.date" content="2026-09-05">

<title>Take-home Exercise 1 - Technical Report – ISSS626 GAA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f7ac19f99b1bffdb182407b6a99bda4a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ISSS626 GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../hands-on_exercise/hands-on_exercise_1.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hands-on_exercise/hands-on_exercise_2.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hands-on_exercise/hands-on_exercise_3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hands-on_exercise/hands-on_exercise_4.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hands-on_exercise/hands-on_exercise_5.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../in-class_exercise/in-class_ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../in-class_exercise/in-class_ex4.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../in-class_exercise/in-class_ex5.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../take-home_exercise/take-home_ex1_tr.html">
 <span class="dropdown-text">Take-home Exercise 1 - Technical Report</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../take-home_exercise/take-home_ex1_slide.html">
 <span class="dropdown-text">Take-home Exercise 1 - Executive Summary</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#loading-necessary-r-packages" id="toc-loading-necessary-r-packages" class="nav-link" data-scroll-target="#loading-necessary-r-packages">Loading Necessary R Packages</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">1 Data Preparation</a>
  <ul class="collapse">
  <li><a href="#data-import-and-initial-quality-assessment" id="toc-data-import-and-initial-quality-assessment" class="nav-link" data-scroll-target="#data-import-and-initial-quality-assessment">1.1 Data Import and Initial Quality Assessment</a>
  <ul class="collapse">
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import">1.1.1 Data Import</a></li>
  <li><a href="#restrict-to-2022" id="toc-restrict-to-2022" class="nav-link" data-scroll-target="#restrict-to-2022">1.1.2 Restrict to 2022</a></li>
  <li><a href="#initial-data-screening" id="toc-initial-data-screening" class="nav-link" data-scroll-target="#initial-data-screening">1.1.3 Initial Data Screening</a></li>
  <li><a href="#missing-value-assessment" id="toc-missing-value-assessment" class="nav-link" data-scroll-target="#missing-value-assessment">1.1.4 Missing Value Assessment</a></li>
  <li><a href="#duplicate-record-assessment" id="toc-duplicate-record-assessment" class="nav-link" data-scroll-target="#duplicate-record-assessment">1.1.5 Duplicate Record Assessment</a></li>
  </ul></li>
  <li><a href="#study-area-definition" id="toc-study-area-definition" class="nav-link" data-scroll-target="#study-area-definition">1.2 Study Area Definition</a>
  <ul class="collapse">
  <li><a href="#select-bangkok-accident-records" id="toc-select-bangkok-accident-records" class="nav-link" data-scroll-target="#select-bangkok-accident-records">1.2.1 Select Bangkok Accident Records</a></li>
  <li><a href="#prepare-bangkok-administrative-boundary" id="toc-prepare-bangkok-administrative-boundary" class="nav-link" data-scroll-target="#prepare-bangkok-administrative-boundary">1.2.2 Prepare Bangkok Administrative Boundary</a></li>
  </ul></li>
  <li><a href="#event-and-attribute-preparation" id="toc-event-and-attribute-preparation" class="nav-link" data-scroll-target="#event-and-attribute-preparation">1.3 Event and Attribute Preparation</a>
  <ul class="collapse">
  <li><a href="#define-accident-events" id="toc-define-accident-events" class="nav-link" data-scroll-target="#define-accident-events">1.3.1 Define accident events</a></li>
  <li><a href="#derive-temporal-attributes" id="toc-derive-temporal-attributes" class="nav-link" data-scroll-target="#derive-temporal-attributes">1.3.2 Derive Temporal Attributes</a></li>
  <li><a href="#derive-accident-severity" id="toc-derive-accident-severity" class="nav-link" data-scroll-target="#derive-accident-severity">1.3.3 Derive Accident Severity</a></li>
  </ul></li>
  <li><a href="#geospatial-data-preparation" id="toc-geospatial-data-preparation" class="nav-link" data-scroll-target="#geospatial-data-preparation">1.4 Geospatial Data Preparation</a>
  <ul class="collapse">
  <li><a href="#coordinate-completeness-assessment" id="toc-coordinate-completeness-assessment" class="nav-link" data-scroll-target="#coordinate-completeness-assessment">1.4.1 Coordinate Completeness Assessment</a></li>
  <li><a href="#convert-records-to-spatial-point-features" id="toc-convert-records-to-spatial-point-features" class="nav-link" data-scroll-target="#convert-records-to-spatial-point-features">1.4.2 Convert Records to Spatial Point Features</a></li>
  <li><a href="#spatial-validation-against-bkk-boundary" id="toc-spatial-validation-against-bkk-boundary" class="nav-link" data-scroll-target="#spatial-validation-against-bkk-boundary">1.4.3 Spatial Validation Against bkk Boundary</a></li>
  <li><a href="#crs-transformation" id="toc-crs-transformation" class="nav-link" data-scroll-target="#crs-transformation">1.4.4 CRS Transformation</a></li>
  </ul></li>
  <li><a href="#road-network-preparation" id="toc-road-network-preparation" class="nav-link" data-scroll-target="#road-network-preparation">1.5 Road Network Preparation</a>
  <ul class="collapse">
  <li><a href="#import-and-inspect-road-network" id="toc-import-and-inspect-road-network" class="nav-link" data-scroll-target="#import-and-inspect-road-network">1.5.1 Import and Inspect Road Network</a></li>
  <li><a href="#select-relevant-road-classes" id="toc-select-relevant-road-classes" class="nav-link" data-scroll-target="#select-relevant-road-classes">1.5.2 Select Relevant Road Classes</a></li>
  <li><a href="#restrict-road-network-to-bkk" id="toc-restrict-road-network-to-bkk" class="nav-link" data-scroll-target="#restrict-road-network-to-bkk">1.5.3 Restrict Road Network to BKK</a></li>
  <li><a href="#clip-network-to-bkk-boundary" id="toc-clip-network-to-bkk-boundary" class="nav-link" data-scroll-target="#clip-network-to-bkk-boundary">1.5.4 Clip Network to bkk Boundary</a></li>
  <li><a href="#network-geometry-preparation-and-validation" id="toc-network-geometry-preparation-and-validation" class="nav-link" data-scroll-target="#network-geometry-preparation-and-validation">1.5.5 Network Geometry Preparation and Validation</a></li>
  </ul></li>
  <li><a href="#point-to-network-validation-and-snapping" id="toc-point-to-network-validation-and-snapping" class="nav-link" data-scroll-target="#point-to-network-validation-and-snapping">1.6 Point-to-Network Validation and Snapping</a>
  <ul class="collapse">
  <li><a href="#point-to-network-distance-assessment" id="toc-point-to-network-distance-assessment" class="nav-link" data-scroll-target="#point-to-network-distance-assessment">1.6.1 Point-to-Network Distance Assessment</a></li>
  <li><a href="#examine-potentially-misaligned-events" id="toc-examine-potentially-misaligned-events" class="nav-link" data-scroll-target="#examine-potentially-misaligned-events">1.6.2 Examine Potentially Misaligned Events</a></li>
  <li><a href="#snap-accident-events-to-road-network" id="toc-snap-accident-events-to-road-network" class="nav-link" data-scroll-target="#snap-accident-events-to-road-network">1.6.3 Snap Accident Events to Road Network</a></li>
  <li><a href="#post-snapping-validation" id="toc-post-snapping-validation" class="nav-link" data-scroll-target="#post-snapping-validation">1.6.4 Post-Snapping Validation</a></li>
  </ul></li>
  <li><a href="#store-analysis-ready-data" id="toc-store-analysis-ready-data" class="nav-link" data-scroll-target="#store-analysis-ready-data">1.7 Store Analysis-Ready Data</a></li>
  </ul></li>
  <li><a href="#network-constrained-spatial-point-pattern-analysis-sppa" id="toc-network-constrained-spatial-point-pattern-analysis-sppa" class="nav-link" data-scroll-target="#network-constrained-spatial-point-pattern-analysis-sppa">2 Network-Constrained Spatial Point-Pattern Analysis (SPPA)</a>
  <ul class="collapse">
  <li><a href="#first-order-network-constrained-sppa-nkde" id="toc-first-order-network-constrained-sppa-nkde" class="nav-link" data-scroll-target="#first-order-network-constrained-sppa-nkde">2.1 First-Order Network-Constrained SPPA (NKDE)</a>
  <ul class="collapse">
  <li><a href="#preparing-lixels-and-sampling-points" id="toc-preparing-lixels-and-sampling-points" class="nav-link" data-scroll-target="#preparing-lixels-and-sampling-points">2.1.1 Preparing Lixels and Sampling Points</a></li>
  <li><a href="#bandwidth-selection" id="toc-bandwidth-selection" class="nav-link" data-scroll-target="#bandwidth-selection">2.1.2 Bandwidth Selection</a></li>
  <li><a href="#estimating-network-accident-intensity" id="toc-estimating-network-accident-intensity" class="nav-link" data-scroll-target="#estimating-network-accident-intensity">2.1.3 Estimating Network Accident Intensity</a></li>
  <li><a href="#spatial-distribution-of-network-accident-intensity" id="toc-spatial-distribution-of-network-accident-intensity" class="nav-link" data-scroll-target="#spatial-distribution-of-network-accident-intensity">2.1.4 Spatial Distribution of Network Accident Intensity</a></li>
  </ul></li>
  <li><a href="#second-order-network-constrained-sppa-network-gk-function" id="toc-second-order-network-constrained-sppa-network-gk-function" class="nav-link" data-scroll-target="#second-order-network-constrained-sppa-network-gk-function">2.2 Second-Order Network-Constrained SPPA (Network G/K function)</a>
  <ul class="collapse">
  <li><a href="#network-gk-functions-analysis" id="toc-network-gk-functions-analysis" class="nav-link" data-scroll-target="#network-gk-functions-analysis">2.2.1 Network G/K Functions Analysis</a></li>
  <li><a href="#network-csr-and-monte-carlo-simulation" id="toc-network-csr-and-monte-carlo-simulation" class="nav-link" data-scroll-target="#network-csr-and-monte-carlo-simulation">2.2.2 Network CSR and Monte Carlo Simulation</a></li>
  <li><a href="#observed-functions-and-simulation-envelopes" id="toc-observed-functions-and-simulation-envelopes" class="nav-link" data-scroll-target="#observed-functions-and-simulation-envelopes">2.2.3 Observed Functions and Simulation Envelopes</a></li>
  </ul></li>
  <li><a href="#overall-integration-and-interpretation" id="toc-overall-integration-and-interpretation" class="nav-link" data-scroll-target="#overall-integration-and-interpretation">2.3 Overall Integration and Interpretation</a></li>
  </ul></li>
  <li><a href="#geovisualisation-and-analytical-interpretation" id="toc-geovisualisation-and-analytical-interpretation" class="nav-link" data-scroll-target="#geovisualisation-and-analytical-interpretation">3 Geovisualisation and Analytical Interpretation</a>
  <ul class="collapse">
  <li><a href="#temporal-animation-design" id="toc-temporal-animation-design" class="nav-link" data-scroll-target="#temporal-animation-design">3.1 Temporal Animation Design</a></li>
  <li><a href="#animated-accident-distribution" id="toc-animated-accident-distribution" class="nav-link" data-scroll-target="#animated-accident-distribution">3.2 Animated Accident Distribution</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">3.3 Interpretation</a></li>
  <li><a href="#link-to-network-constrained-analysis" id="toc-link-to-network-constrained-analysis" class="nav-link" data-scroll-target="#link-to-network-constrained-analysis">3.4 Link to Network-Constrained Analysis</a></li>
  </ul></li>
  <li><a href="#public-safety-planning-and-management" id="toc-public-safety-planning-and-management" class="nav-link" data-scroll-target="#public-safety-planning-and-management">4 Public-Safety Planning and Management</a>
  <ul class="collapse">
  <li><a href="#road-safety-prioritization" id="toc-road-safety-prioritization" class="nav-link" data-scroll-target="#road-safety-prioritization">4.1 Road-Safety Prioritization</a></li>
  <li><a href="#operational-and-strategic-planning-applications" id="toc-operational-and-strategic-planning-applications" class="nav-link" data-scroll-target="#operational-and-strategic-planning-applications">4.2 Operational and Strategic Planning Applications</a></li>
  <li><a href="#limitations-and-further-analysis" id="toc-limitations-and-further-analysis" class="nav-link" data-scroll-target="#limitations-and-further-analysis">4.3 Limitations and Further Analysis</a></li>
  </ul></li>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link" data-scroll-target="#executive-summary">5 Executive Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#ai-tool-use-declaration" id="toc-ai-tool-use-declaration" class="nav-link" data-scroll-target="#ai-tool-use-declaration">AI Tool Use Declaration</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul class="collapse">
  <li><a href="#appendix-a-data-source-documentation" id="toc-appendix-a-data-source-documentation" class="nav-link" data-scroll-target="#appendix-a-data-source-documentation">Appendix A: Data Source Documentation</a></li>
  <li><a href="#appendix-b-summary-of-methodological-decisions" id="toc-appendix-b-summary-of-methodological-decisions" class="nav-link" data-scroll-target="#appendix-b-summary-of-methodological-decisions">Appendix B: Summary of Methodological Decisions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1 - Technical Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jin Jiaying </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 5, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 27, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>Overview</h1>
<p>This Technical Report examines the spatial patterns of road traffic accidents in Bangkok Province in 2022. Road accident records from the <a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022">Thailand Road Accident 2019-2022</a> dataset are integrated with administrative boundary and OpenStreetMap road-network data to support network-constrained spatial point-pattern analysis.</p>
<p>The analysis consists of four main tasks to examine <strong>where road accidents are concentrated along Bangkok’s road network</strong> and <strong>whether these spatial patterns differ from what would be expected under random conditions</strong>:</p>
<ul>
<li><p>Data Preparation and Quality Assessment: Clean and validate the accident records, define the study area, handle missing or invalid coordinates, and prepare the spatial datasets for analysis.</p></li>
<li><p>First-Order Network Analysis: Estimate how accident intensity varies along the road network using Network Kernel Density Estimation (NKDE), and identify road sections with relatively elevated accident intensity.</p></li>
<li><p>Second-Order Analysis: Investigate whether road accidents exhibit statistically significant spatial clustering, with particular attention to clustering along the road network.</p></li>
<li><p>Integration and Interpretation: Compare findings from conventional and network-constrained approaches and discuss their implications for road-safety planning and public-safety management.</p></li>
</ul>
</section>
<section id="loading-necessary-r-packages" class="level1">
<h1>Loading Necessary R Packages</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, lubridate, spNetwork, gganimate, gifski)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>R packages used in this analysis</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Package</th>
<th style="text-align: left;">Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tidyverse</td>
<td style="text-align: left;">Data wrangling, transformation, and visualisation.</td>
</tr>
<tr class="even">
<td style="text-align: left;">sf</td>
<td style="text-align: left;">Reading, manipulating, and transforming spatial vector data.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lubridate</td>
<td style="text-align: left;">Parsing and manipulating date and time variables.</td>
</tr>
<tr class="even">
<td style="text-align: left;">spNetwork</td>
<td style="text-align: left;">Performing network-constrained spatial analysis on linear networks.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gganimate</td>
<td style="text-align: left;">Creating animated geovisualisations of cumulative accident patterns over time.</td>
</tr>
<tr class="even">
<td style="text-align: left;">gifski</td>
<td style="text-align: left;">Rendering and exporting the temporal animation as a GIF file.</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-preparation" class="level1">
<h1>1 Data Preparation</h1>
<section id="data-import-and-initial-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-import-and-initial-quality-assessment">1.1 Data Import and Initial Quality Assessment</h2>
<p>The accident dataset was imported and screened for temporal coverage, missing values, and duplicate records before subsequent processing.</p>
<section id="data-import" class="level3">
<h3 class="anchored" data-anchor-id="data-import">1.1.1 Data Import</h3>
<p>The raw accident dataset was imported into R for initial inspection and pre-processing.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>th_accident_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"take-home_ex1_data/thai_road_accident_2019_2022.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="restrict-to-2022" class="level3">
<h3 class="anchored" data-anchor-id="restrict-to-2022">1.1.2 Restrict to 2022</h3>
<p>Accident records were restricted to 2022 to maintain a consistent study period for subsequent spatial analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>accident_2022 <span class="ot">&lt;-</span> th_accident_raw <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(incident_datetime) <span class="sc">==</span> <span class="dv">2022</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="initial-data-screening" class="level3">
<h3 class="anchored" data-anchor-id="initial-data-screening">1.1.3 Initial Data Screening</h3>
<p>The structure and summary statistics of the 2022 records were examined to identify variable types, value ranges, and potential data-quality issues.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(accident_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 21,032
Columns: 18
$ acc_code                    &lt;dbl&gt; 6566872, 6566880, 5706553, 5485750, 562445…
$ incident_datetime           &lt;dttm&gt; 2022-01-01 00:01:00, 2022-01-01 00:01:00,…
$ report_datetime             &lt;dttm&gt; 2022-01-02 11:45:00, 2022-01-02 11:44:00,…
$ province_th                 &lt;chr&gt; "ชัยนาท", "มหาสารคาม", "ชุมพร", "ภูเก็ต", "อุดร…
$ province_en                 &lt;chr&gt; "Chai Nat", "Maha Sarakham", "Chumphon", "…
$ agency                      &lt;chr&gt; "department of rural roads", "department o…
$ route                       &lt;chr&gt; "เทศบาลตำบลวัดสิงห์ - บ้านน้ำพุ (ช่วงหันคา)", "แยกทา…
$ vehicle_type                &lt;chr&gt; "motorcycle", "motorcycle", "private/passe…
$ presumed_cause              &lt;chr&gt; "driving under the influence of alcohol", …
$ accident_type               &lt;chr&gt; "other", "other", "rollover/fallen on stra…
$ number_of_vehicles_involved &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, …
$ number_of_fatalities        &lt;dbl&gt; 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, …
$ number_of_injuries          &lt;dbl&gt; 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, …
$ weather_condition           &lt;chr&gt; "clear", "dark", "clear", "clear", "clear"…
$ latitude                    &lt;dbl&gt; 15.113158, 16.489238, 10.625082, 7.934514,…
$ longitude                   &lt;dbl&gt; 99.98124, 103.07762, 99.17715, 98.27715, 1…
$ road_description            &lt;chr&gt; "straight road", "straight road", "straigh…
$ slope_description           &lt;chr&gt; "no slope", "no slope", "no slope", "no sl…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(accident_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    acc_code       incident_datetime             report_datetime              
 Min.   :5478917   Min.   :2022-01-01 00:01:00   Min.   :2022-01-01 09:21:00  
 1st Qu.:6288805   1st Qu.:2022-03-30 07:17:30   1st Qu.:2022-05-24 08:56:45  
 Median :6911501   Median :2022-06-20 07:27:30   Median :2022-09-09 08:54:00  
 Mean   :6855258   Mean   :2022-06-26 12:08:51   Mean   :2022-08-29 00:06:59  
 3rd Qu.:7476661   3rd Qu.:2022-09-30 13:54:45   3rd Qu.:2022-12-21 09:37:30  
 Max.   :7571316   Max.   :2022-12-31 23:55:00   Max.   :2023-01-26 13:20:00  
                                                                              
    province_th       province_en          agency            route      
 Length   :21032   Length   :21032   Length   :21032   Length   :21032  
 N.unique :   78   N.unique :   78   N.unique :    3   N.unique : 2275  
 N.blank  :    0   N.blank  :    0   N.blank  :    0   N.blank  :    0  
 Min.nchar:    3   Min.nchar:    3   Min.nchar:   22   Min.nchar:    7  
 Max.nchar:   15   Max.nchar:   24   Max.nchar:   32   Max.nchar:  101  
                                                                        
                                                                        
    vehicle_type     presumed_cause    accident_type  
 Length   :21032   Length   :21032   Length   :21032  
 N.unique :   15   N.unique :   49   N.unique :   11  
 N.blank  :    0   N.blank  :    0   N.blank  :    0  
 Min.nchar:    3   Min.nchar:    5   Min.nchar:    5  
 Max.nchar:   28   Max.nchar:   47   Max.nchar:   44  
                                                      
                                                      
 number_of_vehicles_involved number_of_fatalities number_of_injuries
 Min.   : 0.000              Min.   : 0.0000      Min.   : 0.0000   
 1st Qu.: 1.000              1st Qu.: 0.0000      1st Qu.: 0.0000   
 Median : 1.000              Median : 0.0000      Median : 0.0000   
 Mean   : 1.529              Mean   : 0.1262      Mean   : 0.7688   
 3rd Qu.: 2.000              3rd Qu.: 0.0000      3rd Qu.: 1.0000   
 Max.   :24.000              Max.   :10.0000      Max.   :49.0000   
                                                                    
 weather_condition    latitude        longitude       road_description
 Length   :21032   Min.   : 5.771   Min.   : 97.87   Length   :21032  
 N.unique :    6   1st Qu.:13.502   1st Qu.: 99.89   N.unique :   16  
 N.blank  :    0   Median :14.373   Median :100.61   N.blank  :    0  
 Min.nchar:    4   Mean   :14.358   Mean   :100.83   Min.nchar:    5  
 Max.nchar:   16   3rd Qu.:16.538   3rd Qu.:101.31   Max.nchar:   36  
                   Max.   :20.378   Max.   :105.48                    
                   NAs    :189      NAs    :189                       
 slope_description
 Length   :21032  
 N.unique :    3  
 N.blank  :    0  
 Min.nchar:    5  
 Max.nchar:   10  
                  
                  </code></pre>
</div>
</div>
</section>
<section id="missing-value-assessment" class="level3">
<h3 class="anchored" data-anchor-id="missing-value-assessment">1.1.4 Missing Value Assessment</h3>
<p>Missing values were assessed across all variables to identify fields requiring attention before analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(accident_2022))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   acc_code           incident_datetime 
                          0                           0 
            report_datetime                 province_th 
                          0                           0 
                province_en                      agency 
                          0                           0 
                      route                vehicle_type 
                          0                           0 
             presumed_cause               accident_type 
                          0                           0 
number_of_vehicles_involved        number_of_fatalities 
                          0                           0 
         number_of_injuries           weather_condition 
                          0                           0 
                   latitude                   longitude 
                        189                         189 
           road_description           slope_description 
                          0                           0 </code></pre>
</div>
</div>
</section>
<section id="duplicate-record-assessment" class="level3">
<h3 class="anchored" data-anchor-id="duplicate-record-assessment">1.1.5 Duplicate Record Assessment</h3>
<p>Both fully duplicated records and repeated accident identifiers were checked to avoid unintended double counting.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(accident_2022))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>accident_2022 <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(acc_code) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: acc_code &lt;dbl&gt;, n &lt;int&gt;</code></pre>
</div>
</div>
<p>As result, no duplicated accident identifiers or fully duplicated records were detected.</p>
</section>
</section>
<section id="study-area-definition" class="level2">
<h2 class="anchored" data-anchor-id="study-area-definition">1.2 Study Area Definition</h2>
<p>Bangkok Province was selected as the study area because it provides a clearly defined urban road-safety case while retaining the complete set of accident events within the selected geographic extent.</p>
<p>Restricting the analysis to Bangkok also provides a computationally tractable road network for network-constrained spatial point-pattern analysis without requiring random sub-sampling of accident events.</p>
<section id="select-bangkok-accident-records" class="level3">
<h3 class="anchored" data-anchor-id="select-bangkok-accident-records">1.2.1 Select Bangkok Accident Records</h3>
<p>Accident records were restricted to Bangkok to match the defined study area.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>accident_bkk <span class="ot">&lt;-</span> accident_2022 <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province_en <span class="sc">==</span> <span class="st">"Bangkok"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="prepare-bangkok-administrative-boundary" class="level3">
<h3 class="anchored" data-anchor-id="prepare-bangkok-administrative-boundary">1.2.2 Prepare Bangkok Administrative Boundary</h3>
<p>The Bangkok administrative boundary was extracted to provide the spatial extent for filtering, validation, and visualisation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>tha_adm1 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"take-home_ex1_data/geoBoundaries-THA-ADM1.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-THA-ADM1' from data source 
  `C:\Users\jiayi\Documents\SMU\26_Aug_Term\GAA\lw0170_GAA\ISSS626_course\take-home_exercise\take-home_ex1_data\geoBoundaries-THA-ADM1.geojson' 
  using driver `GeoJSON'
Simple feature collection with 77 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>bkk_boundary <span class="ot">&lt;-</span> tha_adm1 <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(shapeName <span class="sc">==</span> <span class="st">"Bangkok"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Why Use a Spatial Boundary?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why Use a Spatial Boundary?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The province attribute identifies records labelled as Bangkok, while the administrative boundary provides an explicit spatial definition of the study area.</p>
<p>A Spatial Boundary is used here to validate accident locations and to clip the road network to the same spatial extent.</p>
</div>
</div>
</section>
</section>
<section id="event-and-attribute-preparation" class="level2">
<h2 class="anchored" data-anchor-id="event-and-attribute-preparation">1.3 Event and Attribute Preparation</h2>
<p>Accident records were structured as point events and enriched with temporal and severity attributes for subsequent exploratory and spatial analysis.</p>
<section id="define-accident-events" class="level3">
<h3 class="anchored" data-anchor-id="define-accident-events">1.3.1 Define accident events</h3>
<p>A point event represents one recorded road traffic accident occurring within Bangkok Province during 2022. Each unique acc_code is treated as one event.</p>
<p>Multiple accidents occurring at the same recorded coordinates are retained as separate events because they represent distinct accident incidents.</p>
</section>
<section id="derive-temporal-attributes" class="level3">
<h3 class="anchored" data-anchor-id="derive-temporal-attributes">1.3.2 Derive Temporal Attributes</h3>
<p>Month, weekday, and hour were derived from the incident timestamp to support temporal pattern analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>accident_bkk <span class="ot">&lt;-</span> accident_bkk <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">weekday =</span> <span class="fu">wday</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour =</span> <span class="fu">hour</span>(incident_datetime))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="derive-accident-severity" class="level3">
<h3 class="anchored" data-anchor-id="derive-accident-severity">1.3.3 Derive Accident Severity</h3>
<p>Accident severity was derived from reported fatalities and injuries to support severity-based comparison.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>accident_bkk <span class="ot">&lt;-</span> accident_bkk <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">severity =</span> <span class="fu">case_when</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(number_of_fatalities) <span class="sc">|</span> <span class="fu">is.na</span>(number_of_injuries) <span class="sc">~</span> <span class="st">"Unknown"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>      number_of_fatalities <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Fatal"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>      number_of_injuries <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Injury"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Non-injury"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Severity Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Severity Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fatal accidents take precedence over injury accidents when both fatalities and injuries are recorded, while records with missing injury or fatality information are classified as “Unknown”.</p>
</div>
</div>
</section>
</section>
<section id="geospatial-data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="geospatial-data-preparation">1.4 Geospatial Data Preparation</h2>
<p>Accident records were validated spatially, converted to point features, and transformed to a projected coordinate system suitable for distance-based analysis.</p>
<section id="coordinate-completeness-assessment" class="level3">
<h3 class="anchored" data-anchor-id="coordinate-completeness-assessment">1.4.1 Coordinate Completeness Assessment</h3>
<p>Coordinate completeness was assessed before spatial conversion because valid locations are required for point-pattern analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>missing_coord <span class="ot">&lt;-</span> accident_bkk <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(latitude) <span class="sc">|</span> <span class="fu">is.na</span>(longitude))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(missing_coord)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 189</code></pre>
</div>
</div>
<p>Records with missing coordinates were retained during the initial quality assessment but excluded from spatial point-pattern analysis because their locations could not be reliably represented spatially.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>accident_bkk_clean <span class="ot">&lt;-</span> accident_bkk <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(latitude),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(longitude))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="convert-records-to-spatial-point-features" class="level3">
<h3 class="anchored" data-anchor-id="convert-records-to-spatial-point-features">1.4.2 Convert Records to Spatial Point Features</h3>
<p>Valid coordinate records were converted into sf point features using WGS 84 (EPSG:4326), matching the geographic coordinate system of the source coordinates.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>accident_bkk_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  accident_bkk_clean,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">crs =</span> <span class="dv">4326</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="spatial-validation-against-bkk-boundary" class="level3">
<h3 class="anchored" data-anchor-id="spatial-validation-against-bkk-boundary">1.4.3 Spatial Validation Against bkk Boundary</h3>
<p>Accident points were spatially filtered against the Bangkok boundary to remove records whose coordinates were inconsistent with the defined study area.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>accident_bkk_sf <span class="ot">&lt;-</span> <span class="fu">st_filter</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  accident_bkk_sf,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  bkk_boundary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="crs-transformation" class="level3">
<h3 class="anchored" data-anchor-id="crs-transformation">1.4.4 CRS Transformation</h3>
<p>Accident points and the Bangkok boundary were transformed to UTM Zone 47N (EPSG:32647) to support distance-based and network-constrained analysis in metres.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>accident_bkk_utm <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  accident_bkk_sf,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="dv">32647</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>bkk_boundary_utm <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  bkk_boundary,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Why Use a Projected CRS?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why Use a Projected CRS?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Network distances and bandwidths are measured in metres. A projected CRS is therefore required instead of geographic coordinates expressed in degrees.</p>
</div>
</div>
</section>
</section>
<section id="road-network-preparation" class="level2">
<h2 class="anchored" data-anchor-id="road-network-preparation">1.5 Road Network Preparation</h2>
<p>The road network was filtered, clipped, and geometrically prepared to represent the linear space on which network-constrained analysis is performed.</p>
<section id="import-and-inspect-road-network" class="level3">
<h3 class="anchored" data-anchor-id="import-and-inspect-road-network">1.5.1 Import and Inspect Road Network</h3>
<p><a href="https://download.geofabrik.de/asia/thailand.html">The OpenStreetMap road network</a> was imported and inspected for CRS, geometry type, and available road classifications.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>roads_th <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"take-home_ex1_data/th_road/gis_osm_roads_free_1.shp"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `C:\Users\jiayi\Documents\SMU\26_Aug_Term\GAA\lw0170_GAA\ISSS626_course\take-home_exercise\take-home_ex1_data\th_road\gis_osm_roads_free_1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 2930836 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>roads_th</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2930836 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168
Geodetic CRS:  WGS 84
First 10 features:
    osm_id code      fclass                name  ref oneway maxspeed layer
1  4270622 5122 residential ถนนศิริมังคลาจารย์ ซอย1 &lt;NA&gt;      B        0     0
2  4828442 5122 residential    Soi Ruam- U-Thit &lt;NA&gt;      B        0     0
3  4828443 5122 residential    Soi Ruam- U-Thit &lt;NA&gt;      B        0     0
4  4828444 5122 residential                &lt;NA&gt; &lt;NA&gt;      B        0     0
5  4828446 5122 residential                &lt;NA&gt; &lt;NA&gt;      B        0     0
6  8560735 5122 residential   ซอยโรงเรียนจารุณีวิทย์ &lt;NA&gt;      B       30     0
7  8560761 5122 residential    ซอยโรงเรียนกิ่งเพชร &lt;NA&gt;      F       30     0
8  8560767 5122 residential         ซอยเพชรบุรี 5 &lt;NA&gt;      B        0     0
9  8560771 5122 residential        ซอยเพชรบุรี 12 &lt;NA&gt;      F        0     0
10 8560776 5153     footway                &lt;NA&gt; &lt;NA&gt;      B        0     0
   bridge tunnel                       geometry
1       F      F LINESTRING (98.97274 18.796...
2       F      F LINESTRING (98.34197 7.8194...
3       F      F LINESTRING (98.34053 7.8202...
4       F      F LINESTRING (98.34256 7.8210...
5       F      F LINESTRING (98.34197 7.8194...
6       F      F LINESTRING (100.5263 13.753...
7       F      F LINESTRING (100.5257 13.751...
8       F      F LINESTRING (100.5252 13.758...
9       F      F LINESTRING (100.5299 13.753...
10      F      F LINESTRING (100.521 13.7563...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(roads_th)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(roads_th))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] LINESTRING
18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(roads_th<span class="sc">$</span>fclass)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "residential"    "footway"        "secondary"      "motorway"      
 [5] "primary"        "motorway_link"  "primary_link"   "trunk"         
 [9] "unclassified"   "tertiary"       "secondary_link" "trunk_link"    
[13] "service"        "cycleway"       "tertiary_link"  "path"          
[17] "track"          "steps"          "track_grade4"   "track_grade2"  
[21] "living_street"  "track_grade3"   "pedestrian"     "track_grade1"  
[25] "track_grade5"   "busway"         "bridleway"      "unknown"       </code></pre>
</div>
</div>
</section>
<section id="select-relevant-road-classes" class="level3">
<h3 class="anchored" data-anchor-id="select-relevant-road-classes">1.5.2 Select Relevant Road Classes</h3>
<p>Road classes potentially accessible to motor vehicles were retained to construct a road network relevant to traffic accidents.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>motor_road_classes <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"motorway"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"motorway_link"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"trunk"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"trunk_link"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"primary"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"primary_link"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"secondary"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"secondary_link"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tertiary"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tertiary_link"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"unclassified"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"residential"</span>,</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"living_street"</span>,</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"service"</span>)</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>roads_motor <span class="ot">&lt;-</span> roads_th <span class="sc">%&gt;%</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fclass <span class="sc">%in%</span> motor_road_classes)</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>roads_motor <span class="sc">%&gt;%</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(fclass, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           fclass       n
1     residential 1357946
2         service  934108
3    unclassified  117254
4        tertiary   39161
5       secondary   32115
6           trunk   20375
7         primary   19955
8      trunk_link   10638
9    primary_link    8201
10 secondary_link    6702
11       motorway    2671
12  motorway_link    2380
13  tertiary_link    1615
14  living_street      25</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Why Filter Road Classes?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why Filter Road Classes?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Non-motorised or functionally irrelevant paths may not represent plausible locations for road traffic accidents. Thus filtering road classes can reduce network noise while retaining major and local motor-vehicle roads.</p>
</div>
</div>
</section>
<section id="restrict-road-network-to-bkk" class="level3">
<h3 class="anchored" data-anchor-id="restrict-road-network-to-bkk">1.5.3 Restrict Road Network to BKK</h3>
<p>Road features intersecting Bangkok were selected to reduce the network to the study area.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(roads_motor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(bkk_boundary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(roads_motor) <span class="sc">==</span> <span class="fu">st_crs</span>(bkk_boundary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>roads_bkk <span class="ot">&lt;-</span> <span class="fu">st_filter</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  roads_motor,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  bkk_boundary)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(roads_bkk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 207947</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>roads_bkk <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">count</span>(fclass, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           fclass      n
1     residential 118096
2         service  71913
3         primary   4319
4       secondary   4285
5        tertiary   2583
6    primary_link   1517
7    unclassified   1322
8  secondary_link   1129
9   motorway_link   1034
10       motorway    711
11          trunk    574
12     trunk_link    244
13  tertiary_link    214
14  living_street      6</code></pre>
</div>
</div>
</section>
<section id="clip-network-to-bkk-boundary" class="level3">
<h3 class="anchored" data-anchor-id="clip-network-to-bkk-boundary">1.5.4 Clip Network to bkk Boundary</h3>
<p>Selected road features were geometrically clipped to the Bangkok boundary to ensure that the network extent matched the study area.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>roads_bkk <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  roads_bkk,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  bkk_boundary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Filter vs. Clip">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Filter vs.&nbsp;Clip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spatial filtering identifies roads intersecting Bangkok, while geometric intersection trims those roads to the exact study-area boundary.</p>
</div>
</div>
</section>
<section id="network-geometry-preparation-and-validation" class="level3">
<h3 class="anchored" data-anchor-id="network-geometry-preparation-and-validation">1.5.5 Network Geometry Preparation and Validation</h3>
<p>Road geometries were standardised as LINESTRING, checked for validity, assigned unique identifiers, and transformed to the analysis CRS.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>roads_bkk <span class="ot">&lt;-</span> roads_bkk <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"LINESTRING"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(roads_bkk))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] LINESTRING
18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">st_is_valid</span>(roads_bkk))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  TRUE 
208445 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(roads_bkk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 208445</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>roads_bkk <span class="ot">&lt;-</span> roads_bkk <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">LineID =</span> <span class="fu">row_number</span>())</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anyDuplicated</span>(roads_bkk<span class="sc">$</span>LineID)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>roads_bkk_utm <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  roads_bkk,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="point-to-network-validation-and-snapping" class="level2">
<h2 class="anchored" data-anchor-id="point-to-network-validation-and-snapping">1.6 Point-to-Network Validation and Snapping</h2>
<p>Accident locations were compared with the road network before snapping to ensure that positional discrepancies were identified rather than corrected automatically.</p>
<section id="point-to-network-distance-assessment" class="level3">
<h3 class="anchored" data-anchor-id="point-to-network-distance-assessment">1.6.1 Point-to-Network Distance Assessment</h3>
<p>The distance from each accident point to its nearest road segment was calculated to assess positional consistency with the road network.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Output</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
 0.007847  1.594108  3.642014  4.207461  6.304518 25.354173 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          0%          25%          50%          75%          90%          95% 
 0.007846643  1.594107493  3.642014232  6.304517552  9.017007070  9.708299511 
         99%         100% 
11.602590750 25.354172926 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  total over_10m over_20m over_30m over_50m
  &lt;int&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt;    &lt;int&gt;
1  1799       59        1        0        0</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>nearest_road_id <span class="ot">&lt;-</span> <span class="fu">st_nearest_feature</span>(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  accident_bkk_utm,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  roads_bkk_utm)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>nearest_road_dist <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  accident_bkk_utm,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  roads_bkk_utm[nearest_road_id, ],</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_element =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>accident_bkk_utm<span class="sc">$</span>dist_to_road_m <span class="ot">&lt;-</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>(nearest_road_dist)</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(accident_bkk_utm<span class="sc">$</span>dist_to_road_m)</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>  accident_bkk_utm<span class="sc">$</span>dist_to_road_m,</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>, <span class="dv">1</span>),</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>accident_bkk_utm <span class="sc">%&gt;%</span></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">total =</span> <span class="fu">n</span>(),</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">over_10m =</span> <span class="fu">sum</span>(dist_to_road_m <span class="sc">&gt;</span> <span class="dv">10</span>),</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">over_20m =</span> <span class="fu">sum</span>(dist_to_road_m <span class="sc">&gt;</span> <span class="dv">20</span>),</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">over_30m =</span> <span class="fu">sum</span>(dist_to_road_m <span class="sc">&gt;</span> <span class="dv">30</span>),</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">over_50m =</span> <span class="fu">sum</span>(dist_to_road_m <span class="sc">&gt;</span> <span class="dv">50</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Validation Result">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Validation Result
</div>
</div>
<div class="callout-body-container callout-body">
<p>The median point-to-network distance was approximately <strong>3.64 m</strong>, with 95% of accident events located within <strong>9.71 m</strong> of the nearest road.</p>
<p>Only <strong>1 of 1,799</strong> events was more than 20 m from the network, and none exceeded 30 m, indicating strong overall spatial alignment between the accident locations and the road network.</p>
</div>
</div>
</section>
<section id="examine-potentially-misaligned-events" class="level3">
<h3 class="anchored" data-anchor-id="examine-potentially-misaligned-events">1.6.2 Examine Potentially Misaligned Events</h3>
<p>Events more than 20 m from the nearest road were inspected separately to identify potentially misaligned locations before snapping.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Output</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  acc_code latitude longitude dist_to_road_m route             road_description
     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;           
1  7565239     13.6      100.           25.4 ดาวคะนอง -  แสมดำ other           </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_ex1_tr_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>far_accidents <span class="ot">&lt;-</span> accident_bkk_utm <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dist_to_road_m <span class="sc">&gt;</span> <span class="dv">20</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>far_accidents <span class="sc">%&gt;%</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>    acc_code,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    latitude,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>    longitude,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>    dist_to_road_m,</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>    route,</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>    road_description) <span class="sc">%&gt;%</span></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(dist_to_road_m))</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a>far_nearest_id <span class="ot">&lt;-</span> <span class="fu">st_nearest_feature</span>(</span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a>  far_accidents,</span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a>  roads_bkk_utm)</span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a>nearest_lines <span class="ot">&lt;-</span> <span class="fu">st_nearest_points</span>(</span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a>  far_accidents,</span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a>  roads_bkk_utm[far_nearest_id, ],</span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">pairwise =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a>far_area <span class="ot">&lt;-</span> <span class="fu">st_bbox</span>(</span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_buffer</span>(</span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_union</span>(far_accidents),</span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist =</span> <span class="dv">500</span>))</span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb63-30"><a href="#cb63-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_geometry</span>(roads_bkk_utm),</span>
<span id="cb63-31"><a href="#cb63-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlim =</span> <span class="fu">c</span>(far_area[<span class="st">"xmin"</span>], far_area[<span class="st">"xmax"</span>]),</span>
<span id="cb63-32"><a href="#cb63-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(far_area[<span class="st">"ymin"</span>], far_area[<span class="st">"ymax"</span>]),</span>
<span id="cb63-33"><a href="#cb63-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"grey"</span>)</span>
<span id="cb63-34"><a href="#cb63-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-35"><a href="#cb63-35" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb63-36"><a href="#cb63-36" aria-hidden="true" tabindex="-1"></a>  nearest_lines,</span>
<span id="cb63-37"><a href="#cb63-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">add =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-38"><a href="#cb63-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb63-39"><a href="#cb63-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-40"><a href="#cb63-40" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb63-41"><a href="#cb63-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_geometry</span>(far_accidents),</span>
<span id="cb63-42"><a href="#cb63-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">add =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-43"><a href="#cb63-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Why Inspect Before Snapping?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why Inspect Before Snapping?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Automatically snapping all points may conceal substantial positional errors. Distance assessment and visual inspection help to distinguish minor coordinate offsets from potentially problematic locations.</p>
</div>
</div>
</section>
<section id="snap-accident-events-to-road-network" class="level3">
<h3 class="anchored" data-anchor-id="snap-accident-events-to-road-network">1.6.3 Snap Accident Events to Road Network</h3>
<p>Accident events were snapped to the nearest eligible road segment within 30 m to satisfy the network-location requirement of network-constrained Spatial Point-Pattern Analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>accident_snapped <span class="ot">&lt;-</span> <span class="fu">snapPointsToLines2</span>(</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">points =</span> accident_bkk_utm,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">lines =</span> roads_bkk_utm,</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">idField =</span> <span class="st">"LineID"</span>,</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">snap_dist =</span> <span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Why Use a Snap Distance?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why Use a Snap Distance?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A finite snapping tolerance avoids forcing substantially misaligned events onto the network. The 30 m threshold was applied after examining the observed point-to-network distance distribution.</p>
</div>
</div>
</section>
<section id="post-snapping-validation" class="level3">
<h3 class="anchored" data-anchor-id="post-snapping-validation">1.6.4 Post-Snapping Validation</h3>
<p>The snapped events were checked for record count, geometry type, CRS consistency, road assignment, and residual distance to the network.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Output</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1799</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1799</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] POINT
18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  acc_code nearest_line_id
1  6319547             167
2  6566892           27814
3  5837425          184673
4  5837476              45
5  6243286           28945
6  6243252            4201</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 1.980e-11 4.039e-11 4.513e-11 6.597e-11 1.238e-10 </code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_bkk_utm)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_snapped)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(accident_snapped))</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(accident_snapped) <span class="sc">==</span> <span class="fu">st_crs</span>(roads_bkk_utm)</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(accident_snapped<span class="sc">$</span>nearest_line_id))</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>check_road_id <span class="ot">&lt;-</span> <span class="fu">st_nearest_feature</span>(</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  accident_snapped,</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  roads_bkk_utm)</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>check_distance <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>  accident_snapped,</span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>  roads_bkk_utm[check_road_id, ],</span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_element =</span> <span class="cn">TRUE</span>)</span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(check_distance))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="store-analysis-ready-data" class="level2">
<h2 class="anchored" data-anchor-id="store-analysis-ready-data">1.7 Store Analysis-Ready Data</h2>
<p>The validated accidents, road network, and study boundary were stored together as an analysis-ready object to ensure consistent inputs across subsequent analyses.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>analysis_ready <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">accidents =</span> accident_snapped,</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">roads =</span> roads_bkk_utm,</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">boundary =</span> bkk_boundary_utm)</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  analysis_ready,</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"take-home_ex1_data/processed/analysis_ready.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="network-constrained-spatial-point-pattern-analysis-sppa" class="level1">
<h1>2 Network-Constrained Spatial Point-Pattern Analysis (SPPA)</h1>
<p>Reload clean dataset for analysis later.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>analysis_ready <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"take-home_ex1_data/processed/analysis_ready.rds"</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>accident_snapped <span class="ot">&lt;-</span> analysis_ready<span class="sc">$</span>accidents</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>roads_bkk_utm <span class="ot">&lt;-</span> analysis_ready<span class="sc">$</span>roads</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>bkk_boundary_utm <span class="ot">&lt;-</span> analysis_ready<span class="sc">$</span>boundary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="first-order-network-constrained-sppa-nkde" class="level2">
<h2 class="anchored" data-anchor-id="first-order-network-constrained-sppa-nkde">2.1 First-Order Network-Constrained SPPA (NKDE)</h2>
<p>Network Kernel Density Estimation (NKDE) was used to estimate how accident intensity varies along the Bangkok road network. Unlike conventional planar KDE, NKDE constrains distance and smoothing to the road network, making it more appropriate for road accidents whose locations and interactions are inherently network-based.</p>
<section id="preparing-lixels-and-sampling-points" class="level3">
<h3 class="anchored" data-anchor-id="preparing-lixels-and-sampling-points">2.1.1 Preparing Lixels and Sampling Points</h3>
<p>The road network was divided into lixels and represented by regularly distributed sampling points to provide consistent locations for estimating network-based accident intensity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>road_length_m <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_length</span>(roads_bkk_utm))</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(road_length_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
2.900e-03 3.516e+01 6.686e+01 1.254e+02 1.411e+02 1.016e+04 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  road_length_m,</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.25</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.50</span>,</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.75</span>,</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.90</span>,</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.95</span>,</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.99</span>,</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>),</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          0%          25%          50%          75%          90%          95% 
2.939970e-03 3.515602e+01 6.685518e+01 1.411082e+02 2.839047e+02 4.263897e+02 
         99%         100% 
8.574954e+02 1.016364e+04 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lixel Length Selection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Lixel Length Selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>The original road-segment lengths were examined before lixelisation. With a median length of approximately <strong>65 m</strong> and a 90th percentile of approximately <strong>306 m</strong>, a lixel length of <strong>300 m</strong> was selected to subdivide longer roads without unnecessarily fragmenting the already dense urban network. A minimum residual length of <strong>50 m</strong> was used to avoid excessively short remainder segments.</p>
<p>A shorter lixel length would provide finer sampling but increase computational cost, while a longer length could obscure local variation.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>lixel_length <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>min_lixel_length <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>lixels <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lines =</span> roads_bkk_utm,</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lx_length =</span> lixel_length,</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mindist =</span> min_lixel_length)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(roads_bkk_utm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 208445</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(lixels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 231380</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>lixel_length_m <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">st_length</span>(lixels))</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lixel_length_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
  0.00294  37.86591  75.26157 112.96040 166.33159 349.97623 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(lixel_length_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   0.00293997 349.97623066</code></pre>
</div>
</div>
<p>Lixelisation increased the network from 208,445 to 231,380 segments, indicating moderate subdivision without excessive fragmentation.</p>
<p>Sampling points were then placed at the centre of each lixel for NKDE estimation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bandwidth-selection" class="level3">
<h3 class="anchored" data-anchor-id="bandwidth-selection">2.1.2 Bandwidth Selection</h3>
<p>A fixed bandwidth of 500 m was selected as the analytical scale for NKDE to examine relatively local variations in accident intensity along the road network.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Bandwidth Selection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Bandwidth Selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>The bandwidth determines the network distance over which nearby accident events contribute to the estimated intensity. The NKDE results are sensitive to bandwidth selection; therefore, the 500 m bandwidth should be interpreted as an analytical scale for identifying local patterns rather than a uniquely optimal bandwidth.</p>
<p>This relatively local bandwidth preserves more local variation than broader smoothing scales, making it suitable for identifying localised high-intensity road sections.</p>
</div>
</div>
</section>
<section id="estimating-network-accident-intensity" class="level3">
<h3 class="anchored" data-anchor-id="estimating-network-accident-intensity">2.1.3 Estimating Network Accident Intensity</h3>
<p>NKDE was applied to the snapped accident events using a quartic kernel and the selected 500 m fixed bandwidth to estimate accident intensity along the Bangkok road network.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>run_nkde <span class="ot">&lt;-</span> <span class="cf">function</span>(bw_value) {</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nkde</span>(</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lines =</span> roads_bkk_utm,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">events =</span> accident_snapped,</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(accident_snapped)),</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">samples =</span> samples,</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">bw =</span> bw_value,</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">adaptive =</span> <span class="cn">FALSE</span>,</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"simple"</span>,</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">div =</span> <span class="st">"bw"</span>,</span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">agg =</span> <span class="cn">NULL</span>,</span>
<span id="cb89-16"><a href="#cb89-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb89-17"><a href="#cb89-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">10</span>),</span>
<span id="cb89-18"><a href="#cb89-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">verbose =</span> <span class="cn">TRUE</span>,</span>
<span id="cb89-19"><a href="#cb89-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">check =</span> <span class="cn">TRUE</span>)</span>
<span id="cb89-20"><a href="#cb89-20" aria-hidden="true" tabindex="-1"></a>  }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>nkde_500 <span class="ot">&lt;-</span> <span class="fu">run_nkde</span>(<span class="dv">500</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(nkde_500) <span class="sc">==</span> <span class="fu">nrow</span>(samples)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>lixels_nkde <span class="ot">&lt;-</span> lixels <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">nkde =</span> <span class="fu">as.numeric</span>(nkde_500),</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">nkde_km =</span> nkde <span class="sc">*</span> <span class="dv">1000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The resulting NKDE estimates were assigned to the corresponding lixels and converted to accident intensity per kilometer for subsequent analysis and visualization.</p>
</section>
<section id="spatial-distribution-of-network-accident-intensity" class="level3">
<h3 class="anchored" data-anchor-id="spatial-distribution-of-network-accident-intensity">2.1.4 Spatial Distribution of Network Accident Intensity</h3>
<p>The distribution and spatial pattern of the estimated NKDE intensity were examined to identify road sections with relatively elevated accident intensity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lixels_nkde<span class="sc">$</span>nkde_km)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.0000000 0.0000000 0.0000000 0.0001949 0.0000000 0.1059063 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  lixels_nkde<span class="sc">$</span>nkde_km,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.25</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.50</span>,</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.75</span>,</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.90</span>,</span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.95</span>,</span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.99</span>,</span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>),</span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb96-13"><a href="#cb96-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          0%          25%          50%          75%          90%          95% 
0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0001206578 
         99%         100% 
0.0054338064 0.1059062655 </code></pre>
</div>
</div>
<p>The NKDE intensity distribution was <strong>highly right-skewed</strong>, with at least 90% of lixels having an estimated intensity of zero. The intensity increased from approximately 0.00012 at the 95th percentile to 0.00543 at the 99th percentile, indicating that elevated accident intensity was concentrated within a relatively small proportion of the Bangkok road network.</p>
<p>The 95th percentile was used as a descriptive threshold to identify road sections with relatively high estimated accident intensity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>p95_nkde <span class="ot">&lt;-</span> <span class="fu">quantile</span>(</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  lixels_nkde<span class="sc">$</span>nkde_km,</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fl">0.95</span>,</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>high_intensity_lixels <span class="ot">&lt;-</span> lixels_nkde <span class="sc">%&gt;%</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nkde_km <span class="sc">&gt;=</span> p95_nkde)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(high_intensity_lixels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11569</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(high_intensity_lixels) <span class="sc">/</span> <span class="fu">nrow</span>(lixels_nkde) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>A total of 11,569 lixels were classified as high intensity, corresponding to 5% of the analysed network segments.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>p99_nkde <span class="ot">&lt;-</span> <span class="fu">quantile</span>(</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  lixels_nkde<span class="sc">$</span>nkde_km,</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fl">0.99</span>,</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> lixels_nkde,</span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">colour =</span> nkde_km),</span>
<span id="cb103-10"><a href="#cb103-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb103-11"><a href="#cb103-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_c</span>(</span>
<span id="cb103-12"><a href="#cb103-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">option =</span> <span class="st">"viridis"</span>,</span>
<span id="cb103-13"><a href="#cb103-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">trans =</span> <span class="st">"sqrt"</span>,</span>
<span id="cb103-14"><a href="#cb103-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, p99_nkde),</span>
<span id="cb103-15"><a href="#cb103-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">oob =</span> scales<span class="sc">::</span>squish,</span>
<span id="cb103-16"><a href="#cb103-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"Accident intensity</span><span class="sc">\n</span><span class="st">(per km)"</span>) <span class="sc">+</span></span>
<span id="cb103-17"><a href="#cb103-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb103-18"><a href="#cb103-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb103-19"><a href="#cb103-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Network Kernel Density of Road Accidents"</span>,</span>
<span id="cb103-20"><a href="#cb103-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Bangkok, 2022 | Bandwidth = 500 m"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_ex1_tr_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Sqrt-transformed colour scale">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Sqrt-transformed colour scale
</div>
</div>
<div class="callout-body-container callout-body">
<p>The NKDE intensity distribution is highly right-skewed, with most road lixels having zero or very low estimated intensity.</p>
<p>To improve visual differentiation, a square-root transformation was applied to the colour scale and its upper limit was capped at the 99th percentile.</p>
<p>Values above the 99th percentile were retained and mapped to the upper end of the colour scale using scales::squish.</p>
<p>These adjustments affect only the visualization and do not modify the underlying NKDE estimates.</p>
</div>
</div>
<p>The resulting map shows that elevated accident intensity is concentrated along a relatively small number of road corridors, while most of the Bangkok road network exhibits low or zero estimated intensity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> lixels_nkde,</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"grey85"</span>,</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> high_intensity_lixels,</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"red"</span>,</span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> bkk_boundary_utm,</span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="cn">NA</span>,</span>
<span id="cb104-13"><a href="#cb104-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"grey30"</span>,</span>
<span id="cb104-14"><a href="#cb104-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb104-15"><a href="#cb104-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb104-16"><a href="#cb104-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb104-17"><a href="#cb104-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"High-Intensity Road Sections"</span>,</span>
<span id="cb104-18"><a href="#cb104-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Top 5% of NKDE intensity | Bangkok, 2022"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_ex1_tr_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The high-intensity lixels were concentrated along a limited number of road corridors rather than being evenly distributed across the network. Several relatively continuous high-intensity corridors were observed across the western, central, and southern parts of Bangkok, while fewer high-intensity sections appeared in the eastern part of the study area. This suggests that elevated accident intensity is associated with specific road corridors rather than a general city-wide pattern.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretation of High-Intensity Lixels">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of High-Intensity Lixels
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 95th-percentile threshold identifies road sections with relatively high NKDE intensity within the analysed network. It is a descriptive threshold rather than a statistical significance test; formal assessment of spatial clustering is addressed in the subsequent second-order analysis.</p>
</div>
</div>
</section>
</section>
<section id="second-order-network-constrained-sppa-network-gk-function" class="level2">
<h2 class="anchored" data-anchor-id="second-order-network-constrained-sppa-network-gk-function">2.2 Second-Order Network-Constrained SPPA (Network G/K function)</h2>
<p>Second-order network-constrained analysis was conducted using network G/K functions to assess whether accident events exhibited clustering along the road network beyond that expected under Complete Spatial Randomness (CSR), and to identify the network-distance scales at which such clustering occurred.</p>
<section id="network-gk-functions-analysis" class="level3">
<h3 class="anchored" data-anchor-id="network-gk-functions-analysis">2.2.1 Network G/K Functions Analysis</h3>
<p>The network <strong>G function</strong> examines nearest-neighbour relationships between accident events, while the network <strong>K function</strong> evaluates spatial interaction across increasing network distances. Both functions were analysed together to provide complementary evidence of network-based spatial interaction.</p>
</section>
<section id="network-csr-and-monte-carlo-simulation" class="level3">
<h3 class="anchored" data-anchor-id="network-csr-and-monte-carlo-simulation">2.2.2 Network CSR and Monte Carlo Simulation</h3>
<p>Network-based CSR was used as the reference pattern. Under the null hypothesis, accident events are assumed to be randomly and independently distributed over the eligible Bangkok road network. Monte Carlo simulations were then used to generate reference envelopes for comparison with the observed G and K functions.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Hypothesis">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hypothesis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>H₀:</strong> Road accidents are randomly and independently distributed along the Bangkok road network.</p>
<p><strong>H₁:</strong> Road accidents exhibit spatial interaction inconsistent with network CSR.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Parameter Selection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Parameter Selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>A 100 m width was adopted for the network G-function to provide a more stable representation of accident interaction across network-distance bands. Preliminary sensitivity checks indicated that the narrower 50 m width produced substantial short-range fluctuation.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>gk_test <span class="ot">&lt;-</span> <span class="fu">kfunctions</span>(</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lines =</span> roads_bkk_utm,</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">points =</span> accident_snapped,</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="dv">0</span>,</span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">end =</span> <span class="dv">1000</span>,</span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">step =</span> <span class="dv">50</span>,</span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">width =</span> <span class="dv">100</span>,</span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">nsim =</span> <span class="dv">50</span>,</span>
<span id="cb105-11"><a href="#cb105-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">resolution =</span> <span class="dv">50</span>,</span>
<span id="cb105-12"><a href="#cb105-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="cn">TRUE</span>,</span>
<span id="cb105-13"><a href="#cb105-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf_int =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>gk_test<span class="sc">$</span>plotk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_ex1_tr_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>gk_test<span class="sc">$</span>plotg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_ex1_tr_files/figure-html/unnamed-chunk-51-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>gk_test<span class="sc">$</span>values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       obs_k   lower_k    upper_k distances    obs_g   lower_g   upper_g
1    4380.60   0.00000    0.00000         0 18049.99  0.000000  79.93796
2   18049.99   0.00000   79.93796        50 34948.88 31.975184 143.88833
3   34948.88  31.97518  143.88833       100 24285.15 35.572392 172.26630
4   42335.14  51.55998  207.83869       150 23485.77 31.975184 184.65669
5   58434.65  99.52276  290.37464       200 22926.21 31.975184 159.87592
6   65261.35 143.88833  319.75184       250 21103.62 15.987592 156.27871
7   79538.27 147.48553  364.11740       300 20272.27  3.597208 140.29112
8   85533.62 151.08274  412.08018       350 18465.67 15.987592 140.29112
9   98003.94 183.05793  456.44575       400 18993.26 15.987592 127.90073
10 104526.88 227.42349  488.42093       450 19936.53 15.987592 172.26630
11 117940.47 259.39868  577.15207       500 19153.14 15.987592 159.87592
12 123680.01 262.99589  633.90802       550 16978.82  3.597208 143.88833
13 134919.29 303.76425  660.68723       600 17954.07 15.987592 124.30353
14 141634.08 351.72702  705.05280       650 18465.67 31.975184 156.27871
15 153384.96 367.71461  753.01558       700 18145.92 31.975184 156.27871
16 159779.99 394.49383  816.96594       750 17362.52 19.584800 156.27871
17 170747.48 426.46901  868.52593       800 16850.92 47.962776 143.88833
18 176630.91 442.45660  911.29274       850 16307.34 23.182008 184.65669
19 187054.82 510.00418  987.63349       900 17266.60 15.987592 159.87592
20 193897.51 545.57657 1051.58385       950 16211.42 19.584800 172.26630
21 203266.24 577.55176 1124.32740      1000 16579.13 35.572392 200.64428</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether observed functions exceed upper envelopes</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(gk_test<span class="sc">$</span>values<span class="sc">$</span>obs_k[<span class="dv">2</span><span class="sc">:</span><span class="dv">21</span>] <span class="sc">&gt;</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>      gk_test<span class="sc">$</span>values<span class="sc">$</span>upper_k[<span class="dv">2</span><span class="sc">:</span><span class="dv">21</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(gk_test<span class="sc">$</span>values<span class="sc">$</span>obs_g[<span class="dv">2</span><span class="sc">:</span><span class="dv">21</span>] <span class="sc">&gt;</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>      gk_test<span class="sc">$</span>values<span class="sc">$</span>upper_g[<span class="dv">2</span><span class="sc">:</span><span class="dv">21</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="observed-functions-and-simulation-envelopes" class="level3">
<h3 class="anchored" data-anchor-id="observed-functions-and-simulation-envelopes">2.2.3 Observed Functions and Simulation Envelopes</h3>
<p>The observed K function remained above the upper Monte Carlo envelope across the examined network-distance scales, indicating stronger cumulative spatial clustering than expected under network-based CSR.</p>
<p>Similarly, the observed G function remained above the upper simulation envelope throughout the displayed distance bands. The strongest observed interaction occurred at short network distances, with the G-function reaching its highest value around 50 m before generally declining as distance increased.</p>
<p>Both functions provide consistent evidence against network-based CSR. The G function highlights strong short-range interaction between accident events, while the K function indicates that clustering persists cumulatively across broader network-distance scales.</p>
</section>
</section>
<section id="overall-integration-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="overall-integration-and-interpretation">2.3 Overall Integration and Interpretation</h2>
<p>The first and second order analyses provide complementary perspectives on the spatial pattern of road accidents in Bangkok. NKDE identifies where accident intensity is concentrated along the road network, while the network G and K functions assess whether and at what spatial scales the observed accident pattern departs from network-based Complete Spatial Randomness.</p>
<p>The NKDE results reveal several concentrated and, in some locations, relatively continuous high-intensity road sections. When considered together with the network G and K function results, these concentrations form part of a broader non-random spatial pattern rather than appearing as isolated high-density locations.</p>
<p>Overall, the combined analyses indicate that road accidents in Bangkok exhibit both localised network intensity and spatial interaction across multiple network-distance scales. However, these findings describe the spatial structure of accident occurrence rather than its underlying causes. Additional information on traffic exposure, road characteristics, and surrounding environmental conditions would be required to explain why particular road corridors experience higher accident intensity.</p>
</section>
</section>
<section id="geovisualisation-and-analytical-interpretation" class="level1">
<h1>3 Geovisualisation and Analytical Interpretation</h1>
<section id="temporal-animation-design" class="level2">
<h2 class="anchored" data-anchor-id="temporal-animation-design">3.1 Temporal Animation Design</h2>
<p>To complement the network-constrained spatial analyses, a temporal animation was developed to examine how the observed accident pattern accumulated throughout 2022.</p>
<p>The cleaned monthly attribute was used to organise accident events into twelve sequential states from January to December.</p>
<p>A cumulative rather than month-by-month display was adopted so that accidents remain visible after their month of occurrence.</p>
<p>This allows the animation to show how the annual spatial pattern gradually emerges over time, while accident severity is retained to distinguish fatal, injury, and non-injury events.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>month_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jan"</span>, <span class="st">"Feb"</span>, <span class="st">"Mar"</span>, <span class="st">"Apr"</span>, <span class="st">"May"</span>, <span class="st">"Jun"</span>,</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Jul"</span>, <span class="st">"Aug"</span>, <span class="st">"Sept"</span>, <span class="st">"Oct"</span>, <span class="st">"Nov"</span>, <span class="st">"Dec"</span>)</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>accident_cumulative <span class="ot">&lt;-</span> accident_snapped <span class="sc">%&gt;%</span></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_num =</span> <span class="fu">match</span>(<span class="fu">as.character</span>(month), month_labels)) <span class="sc">%&gt;%</span></span>
<span id="cb114-8"><a href="#cb114-8" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">uncount</span>(</span>
<span id="cb114-9"><a href="#cb114-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> <span class="dv">13</span> <span class="sc">-</span> month_num,</span>
<span id="cb114-10"><a href="#cb114-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.id =</span> <span class="st">"month_offset"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb114-11"><a href="#cb114-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb114-12"><a href="#cb114-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">display_month_num =</span> month_num <span class="sc">+</span> month_offset <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb114-13"><a href="#cb114-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">display_month =</span> <span class="fu">factor</span>(</span>
<span id="cb114-14"><a href="#cb114-14" aria-hidden="true" tabindex="-1"></a>      month_labels[display_month_num],</span>
<span id="cb114-15"><a href="#cb114-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> month_labels,</span>
<span id="cb114-16"><a href="#cb114-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">ordered =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> roads_bkk,</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"grey80"</span>,</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> accident_cumulative <span class="sc">%&gt;%</span></span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(display_month <span class="sc">==</span> <span class="st">"Dec"</span>),</span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">colour =</span> severity),</span>
<span id="cb115-10"><a href="#cb115-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb115-11"><a href="#cb115-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb115-12"><a href="#cb115-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb115-13"><a href="#cb115-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Road Traffic Accidents in Bangkok"</span>,</span>
<span id="cb115-14"><a href="#cb115-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Cumulative accidents: January–December 2022"</span>,</span>
<span id="cb115-15"><a href="#cb115-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Severity"</span>) <span class="sc">+</span></span>
<span id="cb115-16"><a href="#cb115-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="take-home_ex1_tr_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="animated-accident-distribution" class="level2">
<h2 class="anchored" data-anchor-id="animated-accident-distribution">3.2 Animated Accident Distribution</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>accident_animation <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> roads_bkk,</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"grey80"</span>,</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> accident_cumulative,</span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">colour =</span> severity),</span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb116-10"><a href="#cb116-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb116-11"><a href="#cb116-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transition_states</span>(</span>
<span id="cb116-12"><a href="#cb116-12" aria-hidden="true" tabindex="-1"></a>    display_month,</span>
<span id="cb116-13"><a href="#cb116-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">transition_length =</span> <span class="dv">1</span>,</span>
<span id="cb116-14"><a href="#cb116-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_length =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb116-15"><a href="#cb116-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb116-16"><a href="#cb116-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Cumulative Road Traffic Accidents in Bangkok — {closest_state} 2022"</span>,</span>
<span id="cb116-17"><a href="#cb116-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Accidents accumulated from January to {closest_state}"</span>,</span>
<span id="cb116-18"><a href="#cb116-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Severity"</span>) <span class="sc">+</span></span>
<span id="cb116-19"><a href="#cb116-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb116-20"><a href="#cb116-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb116-21"><a href="#cb116-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/bangkok_accidents_2022.gif" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Bangkok Accident 2022</figcaption>
</figure>
</div>
<p>The resulting animation displays the cumulative distribution of reported road accidents across the Bangkok road network from January to December 2022. Each successive frame incorporates newly recorded accidents while retaining events from previous months.</p>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">3.3 Interpretation</h2>
<p>The cumulative animation illustrates how the observed annual accident pattern progressively developed throughout 2022. As additional events are added over time, accident locations do not appear to accumulate uniformly across the entire road network. Instead, repeated concentrations become increasingly visible along particular parts of the network.</p>
<p>By the later months of the year, the cumulative distribution shows a clearer contrast between road sections with relatively dense accident occurrence and sections with comparatively few recorded events. Fatal, injury, and non-injury accidents are all represented within the evolving pattern, although the animation is intended primarily to visualize their spatial and temporal accumulation rather than to compare severity-specific rates.</p>
<p>Importantly, the increasing number of visible points across successive frames is an inherent consequence of the cumulative design and should not be interpreted as evidence that accident risk increased over the course of the year. A month-specific temporal analysis would be required to evaluate seasonal changes or differences in accident frequency between months.</p>
</section>
<section id="link-to-network-constrained-analysis" class="level2">
<h2 class="anchored" data-anchor-id="link-to-network-constrained-analysis">3.4 Link to Network-Constrained Analysis</h2>
<p>The temporal animation provides a descriptive time dimension to the spatial patterns identified in Section 2. While the animation shows how accident locations progressively accumulate across the network, NKDE summarizes the resulting spatial intensity along road segments and highlights locations with comparatively high accident concentration.</p>
<p>The network G and K functions address a different question by evaluating whether the spatial arrangement of accident events departs from network-based CSR and at what network-distance scales this interaction occurs. The animation should therefore be interpreted as complementary exploratory evidence rather than a statistical test of clustering.</p>
<p>Together, the three perspectives provide a more complete description of the observed accident pattern: the animation shows how the pattern develops over time, NKDE identifies where accident intensity is concentrated, and the network G and K functions assess whether and at what spatial scales the observed spatial arrangement differs from the network-based random reference.</p>
</section>
</section>
<section id="public-safety-planning-and-management" class="level1">
<h1>4 Public-Safety Planning and Management</h1>
<section id="road-safety-prioritization" class="level2">
<h2 class="anchored" data-anchor-id="road-safety-prioritization">4.1 Road-Safety Prioritization</h2>
<p>The NKDE results provide a network-based basis for prioritizing road sections for further road-safety investigation. Rather than allocating attention uniformly across Bangkok, planners can use high-intensity corridors as an initial screening layer for targeted investigation. Importantly, high NKDE intensity should not be interpreted directly as evidence of unsafe road design. Accident concentration may also reflect traffic exposure, road hierarchy, intersection density, land use, or other contextual factors that are not represented in the current dataset.</p>
<p>The identified high-intensity sections can therefore be treated as priority screening locations where more detailed investigation of road design, traffic conditions, intersection characteristics, and surrounding land use may be warranted.</p>
</section>
<section id="operational-and-strategic-planning-applications" class="level2">
<h2 class="anchored" data-anchor-id="operational-and-strategic-planning-applications">4.2 Operational and Strategic Planning Applications</h2>
<p>From an operational perspective, NKDE can support the identification of specific road sections for targeted investigation. These locations may be prioritized for further examination of traffic conditions, junction design, signage, lighting, pedestrian infrastructure, or other locally relevant factors.</p>
<p>From a strategic perspective, the network G and K function results indicate that accident occurrence should not necessarily be considered as a collection of independent locations. The observed clustering across network-distance scales suggests that connected road corridors and surrounding network structure may also be relevant when defining broader road-safety study areas.</p>
<p>The temporal animation adds a monitoring perspective by demonstrating how the annual accident pattern develops as events accumulate. With data covering multiple years, a similar approach could be extended to examine whether identified concentrations persist, emerge, or shift over time.</p>
</section>
<section id="limitations-and-further-analysis" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-further-analysis">4.3 Limitations and Further Analysis</h2>
<ol type="1">
<li><strong>Traffic Exposure</strong></li>
</ol>
<p>Traffic volume and vehicle kilometres travelled are not considered. Therefore, NKDE represents <strong>accident intensity rather than accident risk</strong>.</p>
<ol start="2" type="1">
<li><strong>Bandwidth Selection</strong></li>
</ol>
<p>NKDE results are sensitive to bandwidth selection. The 500 m bandwidth represents a selected analytical scale rather than an optimal value.</p>
<ol start="3" type="1">
<li><strong>Road Network Representation</strong></li>
</ol>
<p>The road network is derived from OpenStreetMap and filtered by road class. Differences in network completeness or classification may affect the results.</p>
<ol start="4" type="1">
<li><strong>Network CSR Assumption</strong></li>
</ol>
<p>Network CSR assumes that accidents are equally likely to occur across the eligible road network. In reality, traffic exposure varies between road sections.</p>
<ol start="5" type="1">
<li><strong>Temporal Coverage</strong></li>
</ol>
<p>Only accident records from 2022 are analysed. The identified patterns may therefore be specific to that year rather than persistent over time.</p>
<ol start="6" type="1">
<li><strong>Reporting and Positional Accuracy</strong></li>
</ol>
<p>Incomplete reporting or inaccurate coordinates may affect the observed pattern. Snapping improves network alignment but does not guarantee the exact accident location.</p>
<ol start="7" type="1">
<li><strong>Accident Severity</strong></li>
</ol>
<p>All accidents are treated equally regardless of severity. The results therefore represent overall accident concentration rather than the concentration of severe or fatal accidents.</p>
</section>
</section>
<section id="executive-summary" class="level1">
<h1>5 Executive Summary</h1>
<p><a href="https://isss-626-course.vercel.app/take-home_exercise/take-home_ex1_slide.html#/title-slide" target="_blank">Executive Summary Slide</a></p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Geofabrik GmbH. (n.d.). <em>OpenStreetMap data extracts</em>. https://download.geofabrik.de/</p>
<p>OpenStreetMap contributors. (n.d.). <em>OpenStreetMap</em>. https://www.openstreetmap.org/</p>
<p>Runfola, D., Anderson, A., Baier, H., Crittenden, M., Dowker, E., Fuhrig, S., Goodman, S., Grimsley, G., Layko, R., Melville, G., Mulder, M., Oberman, R., Panganiban, J., Peckham, S., Seitz, L., Shea, K., Slevin, H., Youngerman, R., &amp; Hobbs, L. (2020). geoBoundaries: A global database of political administrative boundaries. <em>PLOS ONE, 15</em>(4), e0231866. https://doi.org/10.1371/journal.pone.0231866</p>
<p>Okabe, A., &amp; Sugihara, K. (2012). <em>Spatial analysis along networks: Statistical and computational methods</em>. John Wiley &amp; Sons.</p>
<p><em>R for Geospatial Data Science and Analytics: First-order spatial point patterns analysis methods</em>. (2026). https://r4gdsa.netlify.app/chap04</p>
<p><em>R for Geospatial Data Science and Analytics: Second-order spatial point patterns analysis methods</em>. (2026). https://r4gdsa.netlify.app/chap05</p>
<p><em>R for Geospatial Data Science and Analytics: Network-constrained spatial point patterns analysis</em>. (2026). https://r4gdsa.netlify.app/chap07</p>
</section>
<section id="ai-tool-use-declaration" class="level1">
<h1>AI Tool Use Declaration</h1>
<p>Generative AI tools were used as supporting tools for brainstorming, refining written expression, and improving the organisation and presentation of this report.</p>
<p>All analytical procedures, R code, methodological decisions, results, and interpretations were conducted, reviewed, and validated by the author. AI-generated suggestions were critically evaluated and revised where necessary before being incorporated into the report.</p>
<p>AI tools were also consulted for troubleshooting selected R and Quarto implementation issues.</p>
</section>
<section id="appendix" class="level1">
<h1>Appendix</h1>
<section id="appendix-a-data-source-documentation" class="level2">
<h2 class="anchored" data-anchor-id="appendix-a-data-source-documentation">Appendix A: Data Source Documentation</h2>
<div class="cell">
<div id="tbl-data-sources" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Data sources used in the analysis.
</figcaption>
<div aria-describedby="tbl-data-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset</th>
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Geographic Coverage</th>
<th style="text-align: left;">Temporal Coverage</th>
<th style="text-align: left;">Access Date</th>
<th style="text-align: left;">Analytical Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Road Accident Records</td>
<td style="text-align: left;">Thailand Road Accident Dataset (Kaggle)</td>
<td style="text-align: left;">Thailand</td>
<td style="text-align: left;">2019–2022 (2022 selected)</td>
<td style="text-align: left;">12 September 2026</td>
<td style="text-align: left;">Accident point events</td>
</tr>
<tr class="even">
<td style="text-align: left;">Administrative Boundary</td>
<td style="text-align: left;">geoBoundaries (ADM1)</td>
<td style="text-align: left;">Thailand</td>
<td style="text-align: left;">Not applicable</td>
<td style="text-align: left;">21 September 2026</td>
<td style="text-align: left;">Definition and clipping of Bangkok study area</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Road Network</td>
<td style="text-align: left;">OpenStreetMap via Geofabrik</td>
<td style="text-align: left;">Thailand</td>
<td style="text-align: left;">Snapshot at time of download</td>
<td style="text-align: left;">21 September 2026</td>
<td style="text-align: left;">Road network for network-constrained spatial analysis</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="appendix-b-summary-of-methodological-decisions" class="level2">
<h2 class="anchored" data-anchor-id="appendix-b-summary-of-methodological-decisions">Appendix B: Summary of Methodological Decisions</h2>
<div class="cell">
<div id="tbl-methodological-decisions" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-methodological-decisions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Summary of key methodological decisions and analytical settings.
</figcaption>
<div aria-describedby="tbl-methodological-decisions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Decision</th>
<th style="text-align: left;">Selected Setting</th>
<th style="text-align: left;">Basis / Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Study Design</td>
<td style="text-align: left;">Study period</td>
<td style="text-align: left;">2022</td>
<td style="text-align: left;">Defines a consistent one-year analytical window</td>
</tr>
<tr class="even">
<td style="text-align: left;">Study Design</td>
<td style="text-align: left;">Study area</td>
<td style="text-align: left;">Bangkok Province</td>
<td style="text-align: left;">Defines a consistent spatial extent for the analysis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spatial Pre-processing</td>
<td style="text-align: left;">Projected CRS</td>
<td style="text-align: left;">EPSG:32647</td>
<td style="text-align: left;">Enables distance-based analysis in metres</td>
</tr>
<tr class="even">
<td style="text-align: left;">Network Preparation</td>
<td style="text-align: left;">Snapping tolerance</td>
<td style="text-align: left;">30 m</td>
<td style="text-align: left;">Selected based on point-to-network distance validation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">First-order Analysis</td>
<td style="text-align: left;">NKDE bandwidth</td>
<td style="text-align: left;">500 m</td>
<td style="text-align: left;">Selected after bandwidth comparison</td>
</tr>
<tr class="even">
<td style="text-align: left;">First-order Analysis</td>
<td style="text-align: left;">Kernel function</td>
<td style="text-align: left;">Quartic</td>
<td style="text-align: left;">Provides smooth distance-decaying density estimation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Second-order Analysis</td>
<td style="text-align: left;">Distance range</td>
<td style="text-align: left;">0–1,000 m</td>
<td style="text-align: left;">Examines short- to intermediate-range network interaction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Second-order Analysis</td>
<td style="text-align: left;">G-function width</td>
<td style="text-align: left;">100 m</td>
<td style="text-align: left;">Selected to improve stability relative to narrower distance bands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSR Simulation</td>
<td style="text-align: left;">Number of simulations</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">Used to construct Monte Carlo simulation envelopes</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSR Simulation</td>
<td style="text-align: left;">Null model</td>
<td style="text-align: left;">Network CSR</td>
<td style="text-align: left;">Represents random event placement along the eligible road network</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>