---
title: "In-class Exercise 5"
author: "Jin Jiaying"
date: "26 Sep 2026"
date-modified: last-modified
---

# Loading the necessary R packages

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, sfdep)
```

# Getting the Data Into R Environment
```{r}
hunan <- st_read(dsn = "in-class_ex5_data", layer = "Hunan")

hunan2012 <- read_csv("in-class_ex5_data/Hunan_2012.csv")

hunan_GDPPC <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15, 16)
```

# Global Measures of Spatial Association

## Deriveing Queen's contiguity weights: sfdep methods
```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb,
                         style = "W"),
         .before = 1)
```

## Computing Global Moran' I
```{r}
moranI <- global_moran(wm_q$GDPPC,
                       wm_q$nb,
                       wm_q$wt)

glimpse(moranI)
```
## Performing Global Moran' I permutation test
```{r}
set.seed(1234)

global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                  nsim = 99)
```

## Computing Local Moran's I
```{r}
lisa <- wm_q %>%
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
  .before = 1) %>%
  unnest(local_moran)
```

## Plotting LISA map
```{r}
lisa_sig <- lisa %>%
  filter(p_ii_sim < 0.05)

tmap_mode("plot")

tm_shape(lisa) +
  tm_polygons() +
  tm_borders(fill_alpha = 0.5) +
tm_shape(lisa_sig) + 
  tm_polygons(fill = "mean",
              fill.legend = tm_legend(
                text.size = 1.15,
                width = 6
              )) +
  tm_borders(fill_alpha = 0.4) +
  tm_layout(legend.title.size = 1.25)
```