{
  "hash": "1f5d7c456425fdf237e4598dbe96e6ff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1 - Technical Report\"\nauthor: \"Jin Jiaying\"\ndate: \"05 Sep 2026\"\ndate-modified: last-modified\n---\n\n# Overview\n\nThis is Technical Report of Take-home Exercise 1, aiming to examine the spatial patterns of road traffic accidents in the Bangkok Greater Metropolitan Area (BGMA) in 2022. Dataset from Kaggle [Thailand Road Accident 2019-2022](https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022) is used. Administrative boundary data and road network data will also be incorporated to support spatial and network-constrained analyses.\n\nThe analysis consists of four main tasks:\n\n- Data Preparation and Quality Assessment: Clean and validate the accident records, define the study area, handle missing or invalid coordinates, and prepare the spatial datasets for analysis.\n\n- Exploratory and First-Order Analysis: Examine the spatial and temporal distribution of accidents and identify areas or road segments with high accident intensity using methods such as Kernel Density Estimation (KDE) and Network Kernel Density Estimation (NKDE).\n\n- Second-Order Analysis – Investigate whether road accidents exhibit statistically significant spatial clustering, with particular attention to clustering along the road network.\n\n- Integration and Interpretation – Compare findings from conventional and network-constrained approaches and discuss their implications for road-safety planning and public-safety management.\n\n\n# Loading Necessary R Packages\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sf, lubridate, spNetwork)\n```\n:::\n\n\n\n# 1 Data Preparation\n\n## 1.1 Data Import and Initial Quality Assessment\n\n### 1.1.1 Data Import\n\n::: {.cell}\n\n```{.r .cell-code}\nth_accident_raw <- read_csv(\"take-home_ex1_data/thai_road_accident_2019_2022.csv\")\n```\n:::\n\n\n### 1.1.2 Restrict to 2022\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_2022 <- th_accident_raw %>%\n  filter(year(incident_datetime) == 2022)\n```\n:::\n\n\n### 1.1.3 Initial Data Screening\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(accident_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 21,032\nColumns: 18\n$ acc_code                    <dbl> 6566872, 6566880, 5706553, 5485750, 562445…\n$ incident_datetime           <dttm> 2022-01-01 00:01:00, 2022-01-01 00:01:00,…\n$ report_datetime             <dttm> 2022-01-02 11:45:00, 2022-01-02 11:44:00,…\n$ province_th                 <chr> \"ชัยนาท\", \"มหาสารคาม\", \"ชุมพร\", \"ภูเก็ต\", \"อุดร…\n$ province_en                 <chr> \"Chai Nat\", \"Maha Sarakham\", \"Chumphon\", \"…\n$ agency                      <chr> \"department of rural roads\", \"department o…\n$ route                       <chr> \"เทศบาลตำบลวัดสิงห์ - บ้านน้ำพุ (ช่วงหันคา)\", \"แยกทา…\n$ vehicle_type                <chr> \"motorcycle\", \"motorcycle\", \"private/passe…\n$ presumed_cause              <chr> \"driving under the influence of alcohol\", …\n$ accident_type               <chr> \"other\", \"other\", \"rollover/fallen on stra…\n$ number_of_vehicles_involved <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, …\n$ number_of_fatalities        <dbl> 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ number_of_injuries          <dbl> 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, …\n$ weather_condition           <chr> \"clear\", \"dark\", \"clear\", \"clear\", \"clear\"…\n$ latitude                    <dbl> 15.113158, 16.489238, 10.625082, 7.934514,…\n$ longitude                   <dbl> 99.98124, 103.07762, 99.17715, 98.27715, 1…\n$ road_description            <chr> \"straight road\", \"straight road\", \"straigh…\n$ slope_description           <chr> \"no slope\", \"no slope\", \"no slope\", \"no sl…\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(accident_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    acc_code       incident_datetime             report_datetime              \n Min.   :5478917   Min.   :2022-01-01 00:01:00   Min.   :2022-01-01 09:21:00  \n 1st Qu.:6288805   1st Qu.:2022-03-30 07:17:30   1st Qu.:2022-05-24 08:56:45  \n Median :6911501   Median :2022-06-20 07:27:30   Median :2022-09-09 08:54:00  \n Mean   :6855258   Mean   :2022-06-26 12:08:51   Mean   :2022-08-29 00:06:59  \n 3rd Qu.:7476661   3rd Qu.:2022-09-30 13:54:45   3rd Qu.:2022-12-21 09:37:30  \n Max.   :7571316   Max.   :2022-12-31 23:55:00   Max.   :2023-01-26 13:20:00  \n                                                                              \n    province_th       province_en          agency            route      \n Length   :21032   Length   :21032   Length   :21032   Length   :21032  \n N.unique :   78   N.unique :   78   N.unique :    3   N.unique : 2275  \n N.blank  :    0   N.blank  :    0   N.blank  :    0   N.blank  :    0  \n Min.nchar:    3   Min.nchar:    3   Min.nchar:   22   Min.nchar:    7  \n Max.nchar:   15   Max.nchar:   24   Max.nchar:   32   Max.nchar:  101  \n                                                                        \n                                                                        \n    vehicle_type     presumed_cause    accident_type  \n Length   :21032   Length   :21032   Length   :21032  \n N.unique :   15   N.unique :   49   N.unique :   11  \n N.blank  :    0   N.blank  :    0   N.blank  :    0  \n Min.nchar:    3   Min.nchar:    5   Min.nchar:    5  \n Max.nchar:   28   Max.nchar:   47   Max.nchar:   44  \n                                                      \n                                                      \n number_of_vehicles_involved number_of_fatalities number_of_injuries\n Min.   : 0.000              Min.   : 0.0000      Min.   : 0.0000   \n 1st Qu.: 1.000              1st Qu.: 0.0000      1st Qu.: 0.0000   \n Median : 1.000              Median : 0.0000      Median : 0.0000   \n Mean   : 1.529              Mean   : 0.1262      Mean   : 0.7688   \n 3rd Qu.: 2.000              3rd Qu.: 0.0000      3rd Qu.: 1.0000   \n Max.   :24.000              Max.   :10.0000      Max.   :49.0000   \n                                                                    \n weather_condition    latitude        longitude       road_description\n Length   :21032   Min.   : 5.771   Min.   : 97.87   Length   :21032  \n N.unique :    6   1st Qu.:13.502   1st Qu.: 99.89   N.unique :   16  \n N.blank  :    0   Median :14.373   Median :100.61   N.blank  :    0  \n Min.nchar:    4   Mean   :14.358   Mean   :100.83   Min.nchar:    5  \n Max.nchar:   16   3rd Qu.:16.538   3rd Qu.:101.31   Max.nchar:   36  \n                   Max.   :20.378   Max.   :105.48                    \n                   NAs    :189      NAs    :189                       \n slope_description\n Length   :21032  \n N.unique :    3  \n N.blank  :    0  \n Min.nchar:    5  \n Max.nchar:   10  \n                  \n                  \n```\n\n\n:::\n:::\n\n:::\n:::\n\n### 1.1.4 Missing Value Assessment\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(accident_2022))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   acc_code           incident_datetime \n                          0                           0 \n            report_datetime                 province_th \n                          0                           0 \n                province_en                      agency \n                          0                           0 \n                      route                vehicle_type \n                          0                           0 \n             presumed_cause               accident_type \n                          0                           0 \nnumber_of_vehicles_involved        number_of_fatalities \n                          0                           0 \n         number_of_injuries           weather_condition \n                          0                           0 \n                   latitude                   longitude \n                        189                         189 \n           road_description           slope_description \n                          0                           0 \n```\n\n\n:::\n:::\n\n\n### 1.1.5 Duplicate Record Assessment\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(accident_2022))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\naccident_2022 %>%\n  count(acc_code) %>%\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 2\n# ℹ 2 variables: acc_code <dbl>, n <int>\n```\n\n\n:::\n:::\n\nNo duplicated accident identifiers or fully duplicated records were detected.\n\n\n## 1.2 Study Area Definition\n\n### 1.2.1 Define Bangkok Metropolitan Region (BMR)\n[Insert source]\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_provinces <- c(\n  \"Bangkok\",\n  \"Nakhon Pathom\",\n  \"Nonthaburi\",\n  \"Pathum Thani\",\n  \"Samut Prakan\",\n  \"Samut Sakhon\")\n```\n:::\n\n\n### 1.2.2 Select BMR Accident Records\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr <- accident_2022 %>%\n  filter(province_en %in% bmr_provinces)\n```\n:::\n\n\n### 1.2.3 Prepare BMR Administrative Boundary\n\n::: {.cell}\n\n```{.r .cell-code}\ntha_adm1 <- st_read(\"take-home_ex1_data/geoBoundaries-THA-ADM1.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM1' from data source \n  `C:\\Users\\jiayi\\Documents\\SMU\\26_Aug_Term\\GAA\\lw0170_GAA\\ISSS626_course\\take-home_exercise\\take-home_ex1_data\\geoBoundaries-THA-ADM1.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbmr_names <- c(\n  \"Bangkok\",\n  \"Nakhon Pathom Province\",\n  \"Nonthaburi Province\",\n  \"Pathum Thani Province\",\n  \"Samut Prakan Province\",\n  \"Samut Sakhon Province\")\n\nbmr_adm1 <- tha_adm1 %>%\n  filter(shapeName %in% bmr_names)\n```\n:::\n\n\n### 1.2.4 Construct BMR Study Boundary\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_boundary <- bmr_adm1 %>%\n  summarise()\n```\n:::\n\n:::\n:::\n\n\n## 1.3 Event and Attribute Preparation\n\n### 1.3.1 Define accident events\nA point event represents one recorded road traffic accident occurring within the Bangkok Metropolitan Region during 2022. Each unique acc_code is treated as one event. Multiple accidents occurring at the same recorded coordinates are retained as separate events because they represent distinct accident incidents.\n\n### 1.3.2 Derive Temporal Attributes\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr <- accident_bmr %>%\n  mutate(\n    month = month(incident_datetime, label = TRUE),\n    weekday = wday(incident_datetime, label = TRUE),\n    hour = hour(incident_datetime))\n```\n:::\n\n\n### 1.3.3 Derive Accident Severity\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr <- accident_bmr %>%\n  mutate(\n    severity = case_when(\n      is.na(number_of_fatalities) | is.na(number_of_injuries) ~ \"Unknown\",\n      number_of_fatalities > 0 ~ \"Fatal\",\n      number_of_injuries > 0 ~ \"Injury\",\n      TRUE ~ \"Non-injury\"))\n```\n:::\n\n\n\n## 1.4 Geospatial Data Preparation\n\n### 1.4.1 Coordinate Completeness and Plausibility\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_coord <- accident_bmr %>%\n  filter(is.na(latitude) | is.na(longitude))\n\nnrow(missing_coord)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 189\n```\n\n\n:::\n:::\n\n:::\nRecords with missing coordinates were retained during the initial quality assessment but excluded from spatial point-pattern analysis because their locations could not be reliably represented spatially.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr_clean <- accident_bmr %>%\n  filter(\n    !is.na(latitude),\n    !is.na(longitude))\n```\n:::\n\n\n### 1.4.2 Convert Records to Spatial Point Features\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr_sf <- st_as_sf(\n  accident_bmr_clean,\n  coords = c(\"longitude\", \"latitude\"),\n  crs = 4326,\n  remove = FALSE)\n```\n:::\n\n\n### 1.4.3 Spatial Validation Against BMR Boundary\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr_sf <- st_filter(\n  accident_bmr_sf,\n  bmr_boundary)\n```\n:::\n\n\n### 1.4.4 CRS Transformation\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr_utm <- st_transform(\n  accident_bmr_sf,\n  32647)\n\nbmr_boundary_utm <- st_transform(\n  bmr_boundary,\n  32647)\n```\n:::\n\n\n\n## 1.5 Road Network Preparation\nThe road network represents an OpenStreetMap snapshot near the end of the 2022 study period; therefore, minor changes to the network during 2022 may not be fully represented.(https://download.geofabrik.de/asia/thailand.html)\n\n### 1.5.1 Import and Inspect Road Network\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_th <- st_read(\"take-home_ex1_data/th_road/gis_osm_roads_free_1.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gis_osm_roads_free_1' from data source \n  `C:\\Users\\jiayi\\Documents\\SMU\\26_Aug_Term\\GAA\\lw0170_GAA\\ISSS626_course\\take-home_exercise\\take-home_ex1_data\\th_road\\gis_osm_roads_free_1.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 2930836 features and 10 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nroads_th\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 2930836 features and 10 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168\nGeodetic CRS:  WGS 84\nFirst 10 features:\n    osm_id code      fclass                name  ref oneway maxspeed layer\n1  4270622 5122 residential ถนนศิริมังคลาจารย์ ซอย1 <NA>      B        0     0\n2  4828442 5122 residential    Soi Ruam- U-Thit <NA>      B        0     0\n3  4828443 5122 residential    Soi Ruam- U-Thit <NA>      B        0     0\n4  4828444 5122 residential                <NA> <NA>      B        0     0\n5  4828446 5122 residential                <NA> <NA>      B        0     0\n6  8560735 5122 residential   ซอยโรงเรียนจารุณีวิทย์ <NA>      B       30     0\n7  8560761 5122 residential    ซอยโรงเรียนกิ่งเพชร <NA>      F       30     0\n8  8560767 5122 residential         ซอยเพชรบุรี 5 <NA>      B        0     0\n9  8560771 5122 residential        ซอยเพชรบุรี 12 <NA>      F        0     0\n10 8560776 5153     footway                <NA> <NA>      B        0     0\n   bridge tunnel                       geometry\n1       F      F LINESTRING (98.97274 18.796...\n2       F      F LINESTRING (98.34197 7.8194...\n3       F      F LINESTRING (98.34053 7.8202...\n4       F      F LINESTRING (98.34256 7.8210...\n5       F      F LINESTRING (98.34197 7.8194...\n6       F      F LINESTRING (100.5263 13.753...\n7       F      F LINESTRING (100.5257 13.751...\n8       F      F LINESTRING (100.5252 13.758...\n9       F      F LINESTRING (100.5299 13.753...\n10      F      F LINESTRING (100.521 13.7563...\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(roads_th)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(st_geometry_type(roads_th))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] LINESTRING\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(roads_th$fclass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"residential\"    \"footway\"        \"secondary\"      \"motorway\"      \n [5] \"primary\"        \"motorway_link\"  \"primary_link\"   \"trunk\"         \n [9] \"unclassified\"   \"tertiary\"       \"secondary_link\" \"trunk_link\"    \n[13] \"service\"        \"cycleway\"       \"tertiary_link\"  \"path\"          \n[17] \"track\"          \"steps\"          \"track_grade4\"   \"track_grade2\"  \n[21] \"living_street\"  \"track_grade3\"   \"pedestrian\"     \"track_grade1\"  \n[25] \"track_grade5\"   \"busway\"         \"bridleway\"      \"unknown\"       \n```\n\n\n:::\n:::\n\n\n### 1.5.2 Select Relevant Road Classes\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_road_classes <- c(\n  \"motorway\",\n  \"motorway_link\",\n  \"trunk\",\n  \"trunk_link\",\n  \"primary\",\n  \"primary_link\",\n  \"secondary\",\n  \"secondary_link\",\n  \"tertiary\",\n  \"tertiary_link\",\n  \"unclassified\",\n  \"residential\",\n  \"living_street\",\n  \"service\")\n\nroads_motor <- roads_th %>%\n  filter(fclass %in% motor_road_classes)\n\nroads_motor %>%\n  st_drop_geometry() %>%\n  count(fclass, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           fclass       n\n1     residential 1357946\n2         service  934108\n3    unclassified  117254\n4        tertiary   39161\n5       secondary   32115\n6           trunk   20375\n7         primary   19955\n8      trunk_link   10638\n9    primary_link    8201\n10 secondary_link    6702\n11       motorway    2671\n12  motorway_link    2380\n13  tertiary_link    1615\n14  living_street      25\n```\n\n\n:::\n:::\n\n\n### 1.5.3 Restrict Road Network to BMR\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(roads_motor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(bmr_boundary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(roads_motor) == st_crs(bmr_boundary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- st_filter(\n  roads_motor,\n  bmr_boundary)\n\nnrow(roads_bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 576872\n```\n\n\n:::\n\n```{.r .cell-code}\nroads_bmr %>%\n  st_drop_geometry() %>%\n   count(fclass, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           fclass      n\n1     residential 276993\n2         service 263244\n3       secondary   7340\n4    unclassified   7222\n5         primary   6270\n6        tertiary   5727\n7    primary_link   2452\n8  secondary_link   2073\n9   motorway_link   1720\n10          trunk   1464\n11       motorway   1268\n12     trunk_link    668\n13  tertiary_link    425\n14  living_street      6\n```\n\n\n:::\n:::\n\n\n### 1.5.4 Clip Network to BMR Boundary\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- st_intersection(\n  roads_bmr,\n  bmr_boundary)\n```\n:::\n\n\n### 1.5.5 Network Geometry Preparation and Validation\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- roads_bmr %>%\n  st_cast(\"LINESTRING\")\nunique(st_geometry_type(roads_bmr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] LINESTRING\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(st_is_valid(roads_bmr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  TRUE \n577626 \n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(roads_bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 577626\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- roads_bmr %>%\n  mutate(LineID = row_number())\n\nanyDuplicated(roads_bmr$LineID)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr_utm <- st_transform(\n  roads_bmr,\n  32647)\n```\n:::\n\n\n\n## 1.6 Point-to-Network Validation and Snapping\n\n### 1.6.1 Point-to-Network Distance Assessment\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_road_id <- st_nearest_feature(\n  accident_bmr_utm,\n  roads_bmr_utm)\n\nnearest_road_dist <- st_distance(\n  accident_bmr_utm,\n  roads_bmr_utm[nearest_road_id, ],\n  by_element = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bmr_utm$dist_to_road_m <-\n  as.numeric(nearest_road_dist)\n\nsummary(accident_bmr_utm$dist_to_road_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n 0.000601  1.851901  3.845640  4.569081  6.599110 41.534161 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(\n  accident_bmr_utm$dist_to_road_m,\n  probs = c(\n    0,\n    0.25,\n    0.5,\n    0.75,\n    0.90,\n    0.95,\n    0.99,\n    1),\n  na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          0%          25%          50%          75%          90%          95% \n6.012547e-04 1.851901e+00 3.845640e+00 6.599110e+00 9.240770e+00 1.057616e+01 \n         99%         100% \n1.395806e+01 4.153416e+01 \n```\n\n\n:::\n\n```{.r .cell-code}\naccident_bmr_utm %>%\n  st_drop_geometry() %>%\n  summarise(\n    total = n(),\n    over_10m = sum(dist_to_road_m > 10),\n    over_20m = sum(dist_to_road_m > 20),\n    over_30m = sum(dist_to_road_m > 30),\n    over_50m = sum(dist_to_road_m > 50))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  total over_10m over_20m over_30m over_50m\n  <int>    <int>    <int>    <int>    <int>\n1  3589      233       19        1        0\n```\n\n\n:::\n:::\n\n:::\nPoint-to-Network Validation\nBefore conducting network-constrained spatial analysis, the distance from each accident point to its nearest road segment was calculated to assess positional consistency. The median distance was approximately 3.85 m, while 95% and 99% of accident locations were within approximately 10.58 m and 13.96 m of the nearest road, respectively. The maximum observed distance was approximately 41.53 m. These results suggest that the accident locations were generally well aligned with the road network. A maximum snapping tolerance of 50 m was therefore considered appropriate for projecting accident points onto the road network.\n:::\n\n### 1.6.2 Examine Potentially Misaligned Events\n\n::: {.cell}\n\n```{.r .cell-code}\nfar_accidents <- accident_bmr_utm %>%\n  filter(dist_to_road_m > 20)\n\nfar_accidents %>%\n  st_drop_geometry() %>%\n  select(\n    acc_code,\n    latitude,\n    longitude,\n    dist_to_road_m,\n    route,\n    road_description) %>%\n  arrange(desc(dist_to_road_m))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 19 × 6\n   acc_code latitude longitude dist_to_road_m route             road_description\n      <dbl>    <dbl>     <dbl>          <dbl> <chr>             <chr>           \n 1  7212324     14.0      101.           41.5 แยกทางหลวงหมายเล… straight road   \n 2  6252745     14.0      100.           27.2 คลองบางหลวง - ต่า… straight road   \n 3  6362572     14.0      100.           26.4 คลองบางไผ่ - คลอง… straight road   \n 4  6233643     14.0      100.           26.3 คลองบางไผ่ - คลอง… straight road   \n 5  7561795     14.0      100.           26.1 คลองบางไผ่ - คลอง… straight road   \n 6  7565239     13.6      100.           25.4 ดาวคะนอง -  แสมดำ other           \n 7  7561793     14.0      100.           25.3 คลองบางไผ่ - คลอง… straight road   \n 8  6513957     14.0      100.           25.2 คลองบางไผ่ - คลอง… straight road   \n 9  7565191     14.0      100.           25.1 คลองบางไผ่ - คลอง… straight road   \n10  6242101     14.0      100.           24.8 คลองบางไผ่ - คลอง… straight road   \n11  7512256     14.0      100.           24.8 ไม่ทราบ            straight road   \n12  6591417     14.0      100.           24.6 คลองบางไผ่ - คลอง… straight road   \n13  5843213     14.0      100.           23.9 คลองบางไผ่ - คลอง… straight road   \n14  7541169     14.0      100.           23.6 คลองบางไผ่ - คลอง… straight road   \n15  6981795     14.0      100.           23.3 คลองบางหลวง - ต่า… other           \n16  7565032     14.0      100.           23.1 คลองบางหลวง - ต่า… wide curve      \n17  6466764     14.0      100.           22.0 คลองบางไผ่ - คลอง… straight road   \n18  7117128     14.0      100.           21.6 คลองบางไผ่ - คลอง… straight road   \n19  7441189     14.0      100.           20.6 ไม่ทราบ            straight road   \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfar_nearest_id <- st_nearest_feature(\n  far_accidents,\n  roads_bmr_utm)\n\nnearest_lines <- st_nearest_points(\n  far_accidents,\n  roads_bmr_utm[far_nearest_id, ],\n  pairwise = TRUE)\n\nfar_area <- st_bbox(\n  st_buffer(\n    st_union(far_accidents),\n    dist = 500))\n\nplot(\n  st_geometry(roads_bmr_utm),\n  xlim = c(far_area[\"xmin\"], far_area[\"xmax\"]),\n  ylim = c(far_area[\"ymin\"], far_area[\"ymax\"]),\n  col = \"grey\")\n\nplot(\n  nearest_lines,\n  add = TRUE,\n  lwd = 2)\n\nplot(\n  st_geometry(far_accidents),\n  add = TRUE,\n  pch = 19)\n```\n\n::: {.cell-output-display}\n![](take-home_ex1_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n:::\nAccident events located more than 20 m from their nearest road segment were visually inspected to identify potential spatial misalignment before network snapping.\n:::\n\n### 1.6.3 Snap Accident Events to Road Network\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_snapped <- snapPointsToLines2(\n  points = accident_bmr_utm,\n  lines = roads_bmr_utm,\n  idField = \"LineID\",\n  snap_dist = 50)\n```\n:::\n\n\n### 1.6.4 Post-Snapping Validation\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(accident_bmr_utm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3589\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(accident_snapped)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3589\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(st_geometry_type(accident_snapped))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] POINT\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(accident_snapped) == st_crs(roads_bmr_utm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(accident_snapped$nearest_line_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\naccident_snapped %>%\n  st_drop_geometry() %>%\n  select(acc_code, nearest_line_id) %>%\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  acc_code nearest_line_id\n1  5652876           12351\n2  5484851          260741\n3  6566824           97053\n4  5485786           10927\n5  5493686           52671\n6  6566830           17321\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_road_id <- st_nearest_feature(\n  accident_snapped,\n  roads_bmr_utm)\n\ncheck_distance <- st_distance(\n  accident_snapped,\n  roads_bmr_utm[check_road_id, ],\n  by_element = TRUE)\n\nsummary(as.numeric(check_distance))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 2.017e-11 4.109e-11 4.549e-11 6.624e-11 1.263e-10 \n```\n\n\n:::\n:::\n\n\n\n## 1.7 Store Analysis-Ready Data\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_ready <- list(\n  accidents = accident_snapped,\n  roads = roads_bmr_utm,\n  boundary = bmr_boundary_utm)\n\nsaveRDS(\n  analysis_ready,\n  \"take-home_ex1_data/processed/analysis_ready.rds\")\n```\n:::\n\n\n\n# 2 First-Order and Second-Order Point-Pattern Analysis\n\n## 2.1 First-Order Point-Pattern Analysis\n\n## 2.2 Second-Order Point-Pattern Analysis\n\n## 2.3 Integration and Interpretation\n\n\n# 3 Geovisualisation and Analytical Interpretation\n\n\n# 4 Public-Safety Planning and Management\n\n\n",
    "supporting": [
      "take-home_ex1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}