{
  "hash": "cb91a22a87c49e94527d41a476de70ef",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1 - Technical Report\"\nauthor: \"Jin Jiaying\"\ndate: \"05 Sep 2026\"\ndate-modified: last-modified\n---\n\n# Overview\n\nThis Technical Report examines the spatial patterns of road traffic accidents in Bangkok Province in 2022. Road accident records from the [Thailand Road Accident 2019-2022](https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022) dataset are integrated with administrative boundary and OpenStreetMap road-network data to support network-constrained spatial point-pattern analysis.\n\nThe analysis consists of four main tasks to examine **where road accidents are concentrated along Bangkok's road network** and **whether these spatial patterns differ from what would be expected under random conditions**:\n\n- Data Preparation and Quality Assessment: Clean and validate the accident records, define the study area, handle missing or invalid coordinates, and prepare the spatial datasets for analysis.\n\n- First-Order Network Analysis: Estimate how accident intensity varies along the road network using Network Kernel Density Estimation (NKDE), and identify road sections with relatively elevated accident intensity.\n\n- Second-Order Analysis: Investigate whether road accidents exhibit statistically significant spatial clustering, with particular attention to clustering along the road network.\n\n- Integration and Interpretation: Compare findings from conventional and network-constrained approaches and discuss their implications for road-safety planning and public-safety management.\n\n\n# Loading Necessary R Packages\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sf, lubridate, spNetwork, gganimate, gifski)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: R packages used in this analysis\n\n|Package   |Purpose                                                                        |\n|:---------|:------------------------------------------------------------------------------|\n|tidyverse |Data wrangling, transformation, and visualisation.                             |\n|sf        |Reading, manipulating, and transforming spatial vector data.                   |\n|lubridate |Parsing and manipulating date and time variables.                              |\n|spNetwork |Performing network-constrained spatial analysis on linear networks.            |\n|gganimate |Creating animated geovisualisations of cumulative accident patterns over time. |\n|gifski    |Rendering and exporting the temporal animation as a GIF file.                  |\n\n\n:::\n:::\n\n\n# 1 Data Preparation\n\n## 1.1 Data Import and Initial Quality Assessment\n\nThe accident dataset was imported and screened for temporal coverage, missing values, and duplicate records before subsequent processing.\n\n### 1.1.1 Data Import\n\nThe raw accident dataset was imported into R for initial inspection and pre-processing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nth_accident_raw <- read_csv(\"take-home_ex1_data/thai_road_accident_2019_2022.csv\")\n```\n:::\n\n\n### 1.1.2 Restrict to 2022\n\nAccident records were restricted to 2022 to maintain a consistent study period for subsequent spatial analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_2022 <- th_accident_raw %>%\n  filter(year(incident_datetime) == 2022)\n```\n:::\n\n\n### 1.1.3 Initial Data Screening\n\nThe structure and summary statistics of the 2022 records were examined to identify variable types, value ranges, and potential data-quality issues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(accident_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 21,032\nColumns: 18\n$ acc_code                    <dbl> 6566872, 6566880, 5706553, 5485750, 562445…\n$ incident_datetime           <dttm> 2022-01-01 00:01:00, 2022-01-01 00:01:00,…\n$ report_datetime             <dttm> 2022-01-02 11:45:00, 2022-01-02 11:44:00,…\n$ province_th                 <chr> \"ชัยนาท\", \"มหาสารคาม\", \"ชุมพร\", \"ภูเก็ต\", \"อุดร…\n$ province_en                 <chr> \"Chai Nat\", \"Maha Sarakham\", \"Chumphon\", \"…\n$ agency                      <chr> \"department of rural roads\", \"department o…\n$ route                       <chr> \"เทศบาลตำบลวัดสิงห์ - บ้านน้ำพุ (ช่วงหันคา)\", \"แยกทา…\n$ vehicle_type                <chr> \"motorcycle\", \"motorcycle\", \"private/passe…\n$ presumed_cause              <chr> \"driving under the influence of alcohol\", …\n$ accident_type               <chr> \"other\", \"other\", \"rollover/fallen on stra…\n$ number_of_vehicles_involved <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, …\n$ number_of_fatalities        <dbl> 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ number_of_injuries          <dbl> 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, …\n$ weather_condition           <chr> \"clear\", \"dark\", \"clear\", \"clear\", \"clear\"…\n$ latitude                    <dbl> 15.113158, 16.489238, 10.625082, 7.934514,…\n$ longitude                   <dbl> 99.98124, 103.07762, 99.17715, 98.27715, 1…\n$ road_description            <chr> \"straight road\", \"straight road\", \"straigh…\n$ slope_description           <chr> \"no slope\", \"no slope\", \"no slope\", \"no sl…\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(accident_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    acc_code       incident_datetime             report_datetime              \n Min.   :5478917   Min.   :2022-01-01 00:01:00   Min.   :2022-01-01 09:21:00  \n 1st Qu.:6288805   1st Qu.:2022-03-30 07:17:30   1st Qu.:2022-05-24 08:56:45  \n Median :6911501   Median :2022-06-20 07:27:30   Median :2022-09-09 08:54:00  \n Mean   :6855258   Mean   :2022-06-26 12:08:51   Mean   :2022-08-29 00:06:59  \n 3rd Qu.:7476661   3rd Qu.:2022-09-30 13:54:45   3rd Qu.:2022-12-21 09:37:30  \n Max.   :7571316   Max.   :2022-12-31 23:55:00   Max.   :2023-01-26 13:20:00  \n                                                                              \n    province_th       province_en          agency            route      \n Length   :21032   Length   :21032   Length   :21032   Length   :21032  \n N.unique :   78   N.unique :   78   N.unique :    3   N.unique : 2275  \n N.blank  :    0   N.blank  :    0   N.blank  :    0   N.blank  :    0  \n Min.nchar:    3   Min.nchar:    3   Min.nchar:   22   Min.nchar:    7  \n Max.nchar:   15   Max.nchar:   24   Max.nchar:   32   Max.nchar:  101  \n                                                                        \n                                                                        \n    vehicle_type     presumed_cause    accident_type  \n Length   :21032   Length   :21032   Length   :21032  \n N.unique :   15   N.unique :   49   N.unique :   11  \n N.blank  :    0   N.blank  :    0   N.blank  :    0  \n Min.nchar:    3   Min.nchar:    5   Min.nchar:    5  \n Max.nchar:   28   Max.nchar:   47   Max.nchar:   44  \n                                                      \n                                                      \n number_of_vehicles_involved number_of_fatalities number_of_injuries\n Min.   : 0.000              Min.   : 0.0000      Min.   : 0.0000   \n 1st Qu.: 1.000              1st Qu.: 0.0000      1st Qu.: 0.0000   \n Median : 1.000              Median : 0.0000      Median : 0.0000   \n Mean   : 1.529              Mean   : 0.1262      Mean   : 0.7688   \n 3rd Qu.: 2.000              3rd Qu.: 0.0000      3rd Qu.: 1.0000   \n Max.   :24.000              Max.   :10.0000      Max.   :49.0000   \n                                                                    \n weather_condition    latitude        longitude       road_description\n Length   :21032   Min.   : 5.771   Min.   : 97.87   Length   :21032  \n N.unique :    6   1st Qu.:13.502   1st Qu.: 99.89   N.unique :   16  \n N.blank  :    0   Median :14.373   Median :100.61   N.blank  :    0  \n Min.nchar:    4   Mean   :14.358   Mean   :100.83   Min.nchar:    5  \n Max.nchar:   16   3rd Qu.:16.538   3rd Qu.:101.31   Max.nchar:   36  \n                   Max.   :20.378   Max.   :105.48                    \n                   NAs    :189      NAs    :189                       \n slope_description\n Length   :21032  \n N.unique :    3  \n N.blank  :    0  \n Min.nchar:    5  \n Max.nchar:   10  \n                  \n                  \n```\n\n\n:::\n:::\n\n\n### 1.1.4 Missing Value Assessment\n\nMissing values were assessed across all variables to identify fields requiring attention before analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(accident_2022))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   acc_code           incident_datetime \n                          0                           0 \n            report_datetime                 province_th \n                          0                           0 \n                province_en                      agency \n                          0                           0 \n                      route                vehicle_type \n                          0                           0 \n             presumed_cause               accident_type \n                          0                           0 \nnumber_of_vehicles_involved        number_of_fatalities \n                          0                           0 \n         number_of_injuries           weather_condition \n                          0                           0 \n                   latitude                   longitude \n                        189                         189 \n           road_description           slope_description \n                          0                           0 \n```\n\n\n:::\n:::\n\n\n### 1.1.5 Duplicate Record Assessment\n\nBoth fully duplicated records and repeated accident identifiers were checked to avoid unintended double counting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(accident_2022))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\naccident_2022 %>%\n  count(acc_code) %>%\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 2\n# ℹ 2 variables: acc_code <dbl>, n <int>\n```\n\n\n:::\n:::\n\n\nAs result, no duplicated accident identifiers or fully duplicated records were detected.\n\n\n## 1.2 Study Area Definition\n\nBangkok Province was selected as the study area because it provides a clearly defined urban road-safety case while retaining the complete set of accident events within the selected geographic extent.\n\nRestricting the analysis to Bangkok also provides a computationally tractable road network for network-constrained spatial point-pattern analysis without requiring random sub-sampling of accident events.\n\n### 1.2.1 Select Bangkok Accident Records\n\nAccident records were restricted to Bangkok to match the defined study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk <- accident_2022 %>%\n  filter(province_en == \"Bangkok\")\n```\n:::\n\n\n### 1.2.2 Prepare Bangkok Administrative Boundary\n\nThe Bangkok administrative boundary was extracted to provide the spatial extent for filtering, validation, and visualisation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntha_adm1 <- st_read(\"take-home_ex1_data/geoBoundaries-THA-ADM1.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM1' from data source \n  `C:\\Users\\jiayi\\Documents\\SMU\\26_Aug_Term\\GAA\\lw0170_GAA\\ISSS626_course\\take-home_exercise\\take-home_ex1_data\\geoBoundaries-THA-ADM1.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbkk_boundary <- tha_adm1 %>%\n  filter(shapeName == \"Bangkok\")\n```\n:::\n\n:::{.callout-tip title=\"Why Use a Spatial Boundary?\"}\nThe province attribute identifies records labelled as Bangkok, while the administrative boundary provides an explicit spatial definition of the study area.\n\nA Spatial Boundary is used here to validate accident locations and to clip the road network to the same spatial extent.\n:::\n\n\n## 1.3 Event and Attribute Preparation\n\nAccident records were structured as point events and enriched with temporal and severity attributes for subsequent exploratory and spatial analysis.\n\n### 1.3.1 Define accident events\n\nA point event represents one recorded road traffic accident occurring within Bangkok Province during 2022. Each unique acc_code is treated as one event.\n\nMultiple accidents occurring at the same recorded coordinates are retained as separate events because they represent distinct accident incidents.\n\n### 1.3.2 Derive Temporal Attributes\n\nMonth, weekday, and hour were derived from the incident timestamp to support temporal pattern analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk <- accident_bkk %>%\n  mutate(\n    month = month(incident_datetime, label = TRUE),\n    weekday = wday(incident_datetime, label = TRUE),\n    hour = hour(incident_datetime))\n```\n:::\n\n\n### 1.3.3 Derive Accident Severity\n\nAccident severity was derived from reported fatalities and injuries to support severity-based comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk <- accident_bkk %>%\n  mutate(\n    severity = case_when(\n      is.na(number_of_fatalities) | is.na(number_of_injuries) ~ \"Unknown\",\n      number_of_fatalities > 0 ~ \"Fatal\",\n      number_of_injuries > 0 ~ \"Injury\",\n      TRUE ~ \"Non-injury\"))\n```\n:::\n\n::: {.callout-note title=\"Severity Definition\"}\nFatal accidents take precedence over injury accidents when both fatalities and injuries are recorded, while records with missing injury or fatality information are classified as \"Unknown\".\n:::\n\n## 1.4 Geospatial Data Preparation\n\nAccident records were validated spatially, converted to point features, and transformed to a projected coordinate system suitable for distance-based analysis.\n\n### 1.4.1 Coordinate Completeness Assessment\n\nCoordinate completeness was assessed before spatial conversion because valid locations are required for point-pattern analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_coord <- accident_bkk %>%\n  filter(is.na(latitude) | is.na(longitude))\n\nnrow(missing_coord)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 189\n```\n\n\n:::\n:::\n\n\nRecords with missing coordinates were retained during the initial quality assessment but excluded from spatial point-pattern analysis because their locations could not be reliably represented spatially.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk_clean <- accident_bkk %>%\n  filter(\n    !is.na(latitude),\n    !is.na(longitude))\n```\n:::\n\n\n### 1.4.2 Convert Records to Spatial Point Features\n\nValid coordinate records were converted into sf point features using WGS 84 (EPSG:4326), matching the geographic coordinate system of the source coordinates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk_sf <- st_as_sf(\n  accident_bkk_clean,\n  coords = c(\"longitude\", \"latitude\"),\n  crs = 4326,\n  remove = FALSE)\n```\n:::\n\n\n### 1.4.3 Spatial Validation Against bkk Boundary\n\nAccident points were spatially filtered against the Bangkok boundary to remove records whose coordinates were inconsistent with the defined study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk_sf <- st_filter(\n  accident_bkk_sf,\n  bkk_boundary)\n```\n:::\n\n\n### 1.4.4 CRS Transformation\n\nAccident points and the Bangkok boundary were transformed to UTM Zone 47N (EPSG:32647) to support distance-based and network-constrained analysis in metres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_bkk_utm <- st_transform(\n  accident_bkk_sf,\n  32647)\n\nbkk_boundary_utm <- st_transform(\n  bkk_boundary,\n  32647)\n```\n:::\n\n::: {.callout-tip title=\"Why Use a Projected CRS?\"}\nNetwork distances and bandwidths are measured in metres. A projected CRS is therefore required instead of geographic coordinates expressed in degrees.\n:::\n\n\n## 1.5 Road Network Preparation\n\nThe road network was filtered, clipped, and geometrically prepared to represent the linear space on which network-constrained analysis is performed.\n\n### 1.5.1 Import and Inspect Road Network\n\n[The OpenStreetMap road network](https://download.geofabrik.de/asia/thailand.html) was imported and inspected for CRS, geometry type, and available road classifications.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_th <- st_read(\"take-home_ex1_data/th_road/gis_osm_roads_free_1.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gis_osm_roads_free_1' from data source \n  `C:\\Users\\jiayi\\Documents\\SMU\\26_Aug_Term\\GAA\\lw0170_GAA\\ISSS626_course\\take-home_exercise\\take-home_ex1_data\\th_road\\gis_osm_roads_free_1.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 2930836 features and 10 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nroads_th\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 2930836 features and 10 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168\nGeodetic CRS:  WGS 84\nFirst 10 features:\n    osm_id code      fclass                name  ref oneway maxspeed layer\n1  4270622 5122 residential ถนนศิริมังคลาจารย์ ซอย1 <NA>      B        0     0\n2  4828442 5122 residential    Soi Ruam- U-Thit <NA>      B        0     0\n3  4828443 5122 residential    Soi Ruam- U-Thit <NA>      B        0     0\n4  4828444 5122 residential                <NA> <NA>      B        0     0\n5  4828446 5122 residential                <NA> <NA>      B        0     0\n6  8560735 5122 residential   ซอยโรงเรียนจารุณีวิทย์ <NA>      B       30     0\n7  8560761 5122 residential    ซอยโรงเรียนกิ่งเพชร <NA>      F       30     0\n8  8560767 5122 residential         ซอยเพชรบุรี 5 <NA>      B        0     0\n9  8560771 5122 residential        ซอยเพชรบุรี 12 <NA>      F        0     0\n10 8560776 5153     footway                <NA> <NA>      B        0     0\n   bridge tunnel                       geometry\n1       F      F LINESTRING (98.97274 18.796...\n2       F      F LINESTRING (98.34197 7.8194...\n3       F      F LINESTRING (98.34053 7.8202...\n4       F      F LINESTRING (98.34256 7.8210...\n5       F      F LINESTRING (98.34197 7.8194...\n6       F      F LINESTRING (100.5263 13.753...\n7       F      F LINESTRING (100.5257 13.751...\n8       F      F LINESTRING (100.5252 13.758...\n9       F      F LINESTRING (100.5299 13.753...\n10      F      F LINESTRING (100.521 13.7563...\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(roads_th)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(st_geometry_type(roads_th))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] LINESTRING\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(roads_th$fclass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"residential\"    \"footway\"        \"secondary\"      \"motorway\"      \n [5] \"primary\"        \"motorway_link\"  \"primary_link\"   \"trunk\"         \n [9] \"unclassified\"   \"tertiary\"       \"secondary_link\" \"trunk_link\"    \n[13] \"service\"        \"cycleway\"       \"tertiary_link\"  \"path\"          \n[17] \"track\"          \"steps\"          \"track_grade4\"   \"track_grade2\"  \n[21] \"living_street\"  \"track_grade3\"   \"pedestrian\"     \"track_grade1\"  \n[25] \"track_grade5\"   \"busway\"         \"bridleway\"      \"unknown\"       \n```\n\n\n:::\n:::\n\n\n### 1.5.2 Select Relevant Road Classes\n\nRoad classes potentially accessible to motor vehicles were retained to construct a road network relevant to traffic accidents.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_road_classes <- c(\n  \"motorway\",\n  \"motorway_link\",\n  \"trunk\",\n  \"trunk_link\",\n  \"primary\",\n  \"primary_link\",\n  \"secondary\",\n  \"secondary_link\",\n  \"tertiary\",\n  \"tertiary_link\",\n  \"unclassified\",\n  \"residential\",\n  \"living_street\",\n  \"service\")\n\nroads_motor <- roads_th %>%\n  filter(fclass %in% motor_road_classes)\n\nroads_motor %>%\n  st_drop_geometry() %>%\n  count(fclass, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           fclass       n\n1     residential 1357946\n2         service  934108\n3    unclassified  117254\n4        tertiary   39161\n5       secondary   32115\n6           trunk   20375\n7         primary   19955\n8      trunk_link   10638\n9    primary_link    8201\n10 secondary_link    6702\n11       motorway    2671\n12  motorway_link    2380\n13  tertiary_link    1615\n14  living_street      25\n```\n\n\n:::\n:::\n\n::: {.callout-tip title=\"Why Filter Road Classes?\"}\nNon-motorised or functionally irrelevant paths may not represent plausible locations for road traffic accidents. Thus filtering road classes can reduce network noise while retaining major and local motor-vehicle roads.\n:::\n\n### 1.5.3 Restrict Road Network to BKK\n\nRoad features intersecting Bangkok were selected to reduce the network to the study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(roads_motor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(bkk_boundary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(roads_motor) == st_crs(bkk_boundary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bkk <- st_filter(\n  roads_motor,\n  bkk_boundary)\n\nnrow(roads_bkk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 207947\n```\n\n\n:::\n\n```{.r .cell-code}\nroads_bkk %>%\n  st_drop_geometry() %>%\n   count(fclass, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           fclass      n\n1     residential 118096\n2         service  71913\n3         primary   4319\n4       secondary   4285\n5        tertiary   2583\n6    primary_link   1517\n7    unclassified   1322\n8  secondary_link   1129\n9   motorway_link   1034\n10       motorway    711\n11          trunk    574\n12     trunk_link    244\n13  tertiary_link    214\n14  living_street      6\n```\n\n\n:::\n:::\n\n\n### 1.5.4 Clip Network to bkk Boundary\n\nSelected road features were geometrically clipped to the Bangkok boundary to ensure that the network extent matched the study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bkk <- st_intersection(\n  roads_bkk,\n  bkk_boundary)\n```\n:::\n\n::: {.callout-tip title=\"Filter vs. Clip\"}\nSpatial filtering identifies roads intersecting Bangkok, while geometric intersection trims those roads to the exact study-area boundary.\n:::\n\n### 1.5.5 Network Geometry Preparation and Validation\n\nRoad geometries were standardised as LINESTRING, checked for validity, assigned unique identifiers, and transformed to the analysis CRS.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bkk <- roads_bkk %>%\n  st_cast(\"LINESTRING\")\nunique(st_geometry_type(roads_bkk))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] LINESTRING\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(st_is_valid(roads_bkk))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  TRUE \n208445 \n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(roads_bkk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 208445\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bkk <- roads_bkk %>%\n  mutate(LineID = row_number())\n\nanyDuplicated(roads_bkk$LineID)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bkk_utm <- st_transform(\n  roads_bkk,\n  32647)\n```\n:::\n\n\n\n## 1.6 Point-to-Network Validation and Snapping\n\nAccident locations were compared with the road network before snapping to ensure that positional discrepancies were identified rather than corrected automatically.\n\n### 1.6.1 Point-to-Network Distance Assessment\n\nThe distance from each accident point to its nearest road segment was calculated to assess positional consistency with the road network.\n\n\n\n::: {.panel-tabset}\n\n## Output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n 0.007847  1.594108  3.642014  4.207461  6.304518 25.354173 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          0%          25%          50%          75%          90%          95% \n 0.007846643  1.594107493  3.642014232  6.304517552  9.017007070  9.708299511 \n         99%         100% \n11.602590750 25.354172926 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  total over_10m over_20m over_30m over_50m\n  <int>    <int>    <int>    <int>    <int>\n1  1799       59        1        0        0\n```\n\n\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_road_id <- st_nearest_feature(\n  accident_bkk_utm,\n  roads_bkk_utm)\n\nnearest_road_dist <- st_distance(\n  accident_bkk_utm,\n  roads_bkk_utm[nearest_road_id, ],\n  by_element = TRUE)\n\naccident_bkk_utm$dist_to_road_m <-\n  as.numeric(nearest_road_dist)\n\nsummary(accident_bkk_utm$dist_to_road_m)\n\nquantile(\n  accident_bkk_utm$dist_to_road_m,\n  probs = c(0, 0.25, 0.5, 0.75, 0.90, 0.95, 0.99, 1),\n  na.rm = TRUE)\n\naccident_bkk_utm %>%\n  st_drop_geometry() %>%\n  summarise(\n    total = n(),\n    over_10m = sum(dist_to_road_m > 10),\n    over_20m = sum(dist_to_road_m > 20),\n    over_30m = sum(dist_to_road_m > 30),\n    over_50m = sum(dist_to_road_m > 50))\n```\n:::\n\n\n:::\n\n::: {.callout-note title=\"Validation Result\"}\nThe median point-to-network distance was approximately **3.64 m**, with 95% of accident events located within **9.71 m** of the nearest road.\n\nOnly **1 of 1,799** events was more than 20 m from the network, and none exceeded 30 m, indicating strong overall spatial alignment between the accident locations and the road network.\n:::\n\n### 1.6.2 Examine Potentially Misaligned Events\n\nEvents more than 20 m from the nearest road were inspected separately to identify potentially misaligned locations before snapping.\n\n\n\n\n::: {.panel-tabset}\n\n## Output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  acc_code latitude longitude dist_to_road_m route             road_description\n     <dbl>    <dbl>     <dbl>          <dbl> <chr>             <chr>           \n1  7565239     13.6      100.           25.4 ดาวคะนอง -  แสมดำ other           \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](take-home_ex1_tr_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfar_accidents <- accident_bkk_utm %>%\n  filter(dist_to_road_m > 20)\n\nfar_accidents %>%\n  st_drop_geometry() %>%\n  select(\n    acc_code,\n    latitude,\n    longitude,\n    dist_to_road_m,\n    route,\n    road_description) %>%\n  arrange(desc(dist_to_road_m))\n\nfar_nearest_id <- st_nearest_feature(\n  far_accidents,\n  roads_bkk_utm)\n\nnearest_lines <- st_nearest_points(\n  far_accidents,\n  roads_bkk_utm[far_nearest_id, ],\n  pairwise = TRUE)\n\nfar_area <- st_bbox(\n  st_buffer(\n    st_union(far_accidents),\n    dist = 500))\n\nplot(\n  st_geometry(roads_bkk_utm),\n  xlim = c(far_area[\"xmin\"], far_area[\"xmax\"]),\n  ylim = c(far_area[\"ymin\"], far_area[\"ymax\"]),\n  col = \"grey\")\n\nplot(\n  nearest_lines,\n  add = TRUE,\n  lwd = 2)\n\nplot(\n  st_geometry(far_accidents),\n  add = TRUE,\n  pch = 19)\n```\n:::\n\n:::\n\n::: {.callout-tip title=\"Why Inspect Before Snapping?\"}\nAutomatically snapping all points may conceal substantial positional errors. Distance assessment and visual inspection help to distinguish minor coordinate offsets from potentially problematic locations.\n:::\n\n### 1.6.3 Snap Accident Events to Road Network\n\nAccident events were snapped to the nearest eligible road segment within 30 m to satisfy the network-location requirement of network-constrained Spatial Point-Pattern Analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_snapped <- snapPointsToLines2(\n  points = accident_bkk_utm,\n  lines = roads_bkk_utm,\n  idField = \"LineID\",\n  snap_dist = 30)\n```\n:::\n\n::: {.callout-tip title=\"Why Use a Snap Distance?\"}\nA finite snapping tolerance avoids forcing substantially misaligned events onto the network. The 30 m threshold was applied after examining the observed point-to-network distance distribution.\n:::\n\n### 1.6.4 Post-Snapping Validation\n\nThe snapped events were checked for record count, geometry type, CRS consistency, road assignment, and residual distance to the network.\n\n::: {.panel-tabset}\n\n## Output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1799\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1799\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] POINT\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  acc_code nearest_line_id\n1  6319547             167\n2  6566892           27814\n3  5837425          184673\n4  5837476              45\n5  6243286           28945\n6  6243252            4201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 1.980e-11 4.039e-11 4.513e-11 6.597e-11 1.238e-10 \n```\n\n\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(accident_bkk_utm)\nnrow(accident_snapped)\n\nunique(st_geometry_type(accident_snapped))\n\nst_crs(accident_snapped) == st_crs(roads_bkk_utm)\n\nsum(is.na(accident_snapped$nearest_line_id))\n\ncheck_road_id <- st_nearest_feature(\n  accident_snapped,\n  roads_bkk_utm)\n\ncheck_distance <- st_distance(\n  accident_snapped,\n  roads_bkk_utm[check_road_id, ],\n  by_element = TRUE)\n\nsummary(as.numeric(check_distance))\n```\n:::\n\n\n:::\n\n## 1.7 Store Analysis-Ready Data\n\nThe validated accidents, road network, and study boundary were stored together as an analysis-ready object to ensure consistent inputs across subsequent analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_ready <- list(\n  accidents = accident_snapped,\n  roads = roads_bkk_utm,\n  boundary = bkk_boundary_utm)\n\nsaveRDS(\n  analysis_ready,\n  \"take-home_ex1_data/processed/analysis_ready.rds\")\n```\n:::\n\n\n\n# 2 Network-Constrained Spatial Point-Pattern Analysis (SPPA)\n\nReload clean dataset for analysis later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_ready <- readRDS(\"take-home_ex1_data/processed/analysis_ready.rds\")\n\naccident_snapped <- analysis_ready$accidents\nroads_bkk_utm <- analysis_ready$roads\nbkk_boundary_utm <- analysis_ready$boundary\n```\n:::\n\n\n## 2.1 First-Order Network-Constrained SPPA (NKDE)\n\nNetwork Kernel Density Estimation (NKDE) was used to estimate how accident intensity varies along the Bangkok road network. Unlike conventional planar KDE, NKDE constrains distance and smoothing to the road network, making it more appropriate for road accidents whose locations and interactions are inherently network-based.\n\n### 2.1.1 Preparing Lixels and Sampling Points\n\nThe road network was divided into lixels and represented by regularly distributed sampling points to provide consistent locations for estimating network-based accident intensity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroad_length_m <- as.numeric(\n  st_length(roads_bkk_utm))\n\nsummary(road_length_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n2.900e-03 3.516e+01 6.686e+01 1.254e+02 1.411e+02 1.016e+04 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(\n  road_length_m,\n  probs = c(\n    0,\n    0.25,\n    0.50,\n    0.75,\n    0.90,\n    0.95,\n    0.99,\n    1),\n  na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          0%          25%          50%          75%          90%          95% \n2.939970e-03 3.515602e+01 6.685518e+01 1.411082e+02 2.839047e+02 4.263897e+02 \n         99%         100% \n8.574954e+02 1.016364e+04 \n```\n\n\n:::\n:::\n\n::: {.callout-tip title=\"Lixel Length Selection\"}\nThe original road-segment lengths were examined before lixelisation. With a median length of approximately **65 m** and a 90th percentile of approximately **306 m**, a lixel length of **300 m** was selected to subdivide longer roads without unnecessarily fragmenting the already dense urban network. A minimum residual length of **50 m** was used to avoid excessively short remainder segments.\n\nA shorter lixel length would provide finer sampling but increase computational cost, while a longer length could obscure local variation.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlixel_length <- 300\nmin_lixel_length <- 50\n\nlixels <- lixelize_lines(\n  lines = roads_bkk_utm,\n  lx_length = lixel_length,\n  mindist = min_lixel_length)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(roads_bkk_utm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 208445\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(lixels)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 231380\n```\n\n\n:::\n\n```{.r .cell-code}\nlixel_length_m <- as.numeric(st_length(lixels))\n\nsummary(lixel_length_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n  0.00294  37.86591  75.26157 112.96040 166.33159 349.97623 \n```\n\n\n:::\n\n```{.r .cell-code}\nrange(lixel_length_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]   0.00293997 349.97623066\n```\n\n\n:::\n:::\n\nLixelisation increased the network from 208,445 to 231,380 segments, indicating moderate subdivision without excessive fragmentation.\n\nSampling points were then placed at the centre of each lixel for NKDE estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamples <- lines_center(lixels)\n```\n:::\n\n\n### 2.1.2 Bandwidth Selection\n\nA fixed bandwidth of 500 m was selected as the analytical scale for NKDE to examine relatively local variations in accident intensity along the road network.\n\n::: {.callout-tip title=\"Bandwidth Selection\"}\nThe bandwidth determines the network distance over which nearby accident events contribute to the estimated intensity. The NKDE results are sensitive to bandwidth selection; therefore, the 500 m bandwidth should be interpreted as an analytical scale for identifying local patterns rather than a uniquely optimal bandwidth.\n\nThis relatively local bandwidth preserves more local variation than broader smoothing scales, making it suitable for identifying localised high-intensity road sections.\n:::\n\n### 2.1.3 Estimating Network Accident Intensity\n\nNKDE was applied to the snapped accident events using a quartic kernel and the selected 500 m fixed bandwidth to estimate accident intensity along the Bangkok road network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_nkde <- function(bw_value) {\n  nkde(\n    lines = roads_bkk_utm,\n    events = accident_snapped,\n    w = rep(1, nrow(accident_snapped)),\n    samples = samples,\n    kernel_name = \"quartic\",\n    bw = bw_value,\n    adaptive = FALSE,\n    method = \"simple\",\n    div = \"bw\",\n    max_depth = 8,\n    digits = 1,\n    tol = 1,\n    agg = NULL,\n    sparse = TRUE,\n    grid_shape = c(10, 10),\n    verbose = TRUE,\n    check = TRUE)\n  }\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnkde_500 <- run_nkde(500)\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(nkde_500) == nrow(samples)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlixels_nkde <- lixels %>%\n  mutate(\n    nkde = as.numeric(nkde_500),\n    nkde_km = nkde * 1000)\n```\n:::\n\n\nThe resulting NKDE estimates were assigned to the corresponding lixels and converted to accident intensity per kilometer for subsequent analysis and visualization.\n\n### 2.1.4 Spatial Distribution of Network Accident Intensity\n\nThe distribution and spatial pattern of the estimated NKDE intensity were examined to identify road sections with relatively elevated accident intensity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lixels_nkde$nkde_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.0000000 0.0000000 0.0000000 0.0001949 0.0000000 0.1059063 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(\n  lixels_nkde$nkde_km,\n  probs = c(\n    0,\n    0.25,\n    0.50,\n    0.75,\n    0.90,\n    0.95,\n    0.99,\n    1),\n  na.rm = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          0%          25%          50%          75%          90%          95% \n0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0001206578 \n         99%         100% \n0.0054338064 0.1059062655 \n```\n\n\n:::\n:::\n\nThe NKDE intensity distribution was **highly right-skewed**, with at least 90% of lixels having an estimated intensity of zero. The intensity increased from approximately 0.00012 at the 95th percentile to 0.00543 at the 99th percentile, indicating that elevated accident intensity was concentrated within a relatively small proportion of the Bangkok road network.\n\nThe 95th percentile was used as a descriptive threshold to identify road sections with relatively high estimated accident intensity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np95_nkde <- quantile(\n  lixels_nkde$nkde_km,\n  probs = 0.95,\n  na.rm = TRUE)\n\nhigh_intensity_lixels <- lixels_nkde %>%\n  filter(nkde_km >= p95_nkde)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(high_intensity_lixels)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11569\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(high_intensity_lixels) / nrow(lixels_nkde) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\nA total of 11,569 lixels were classified as high intensity, corresponding to 5% of the analysed network segments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np99_nkde <- quantile(\n  lixels_nkde$nkde_km,\n  probs = 0.99,\n  na.rm = TRUE)\n\nggplot() +\n  geom_sf(\n    data = lixels_nkde,\n    aes(colour = nkde_km),\n    linewidth = 0.1) +\n  scale_colour_viridis_c(\n    option = \"viridis\",\n    trans = \"sqrt\",\n    limits = c(0, p99_nkde),\n    oob = scales::squish,\n    name = \"Accident intensity\\n(per km)\") +\n  theme_void() +\n  labs(\n    title = \"Network Kernel Density of Road Accidents\",\n    subtitle = \"Bangkok, 2022 | Bandwidth = 500 m\")\n```\n\n::: {.cell-output-display}\n![](take-home_ex1_tr_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n:::{.callout-note title=\"Sqrt-transformed colour scale\"}\nThe NKDE intensity distribution is highly right-skewed, with most road lixels having zero or very low estimated intensity.\n\nTo improve visual differentiation, a square-root transformation was applied to the colour scale and its upper limit was capped at the 99th percentile.\n\nValues above the 99th percentile were retained and mapped to the upper end of the colour scale using scales::squish.\n\nThese adjustments affect only the visualization and do not modify the underlying NKDE estimates.\n:::\n\nThe resulting map shows that elevated accident intensity is concentrated along a relatively small number of road corridors, while most of the Bangkok road network exhibits low or zero estimated intensity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(\n    data = lixels_nkde,\n    colour = \"grey85\",\n    linewidth = 0.15) +\n  geom_sf(\n    data = high_intensity_lixels,\n    colour = \"red\",\n    linewidth = 0.6) +\n  geom_sf(\n    data = bkk_boundary_utm,\n    fill = NA,\n    colour = \"grey30\",\n    linewidth = 0.3) +\n  theme_void() +\n  labs(\n    title = \"High-Intensity Road Sections\",\n    subtitle = \"Top 5% of NKDE intensity | Bangkok, 2022\")\n```\n\n::: {.cell-output-display}\n![](take-home_ex1_tr_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nThe high-intensity lixels were concentrated along a limited number of road corridors rather than being evenly distributed across the network. Several relatively continuous high-intensity corridors were observed across the western, central, and southern parts of Bangkok, while fewer high-intensity sections appeared in the eastern part of the study area. This suggests that elevated accident intensity is associated with specific road corridors rather than a general city-wide pattern.\n\n::: {.callout-note title=\"Interpretation of High-Intensity Lixels\"}\nThe 95th-percentile threshold identifies road sections with relatively high NKDE intensity within the analysed network. It is a descriptive threshold rather than a statistical significance test; formal assessment of spatial clustering is addressed in the subsequent second-order analysis.\n:::\n\n\n## 2.2 Second-Order Network-Constrained SPPA (Network G/K function)\n\nSecond-order network-constrained analysis was conducted using network G/K functions to assess whether accident events exhibited clustering along the road network beyond that expected under Complete Spatial Randomness (CSR), and to identify the network-distance scales at which such clustering occurred.\n\n### 2.2.1 Network G/K Functions Analysis\n\nThe network **G function** examines nearest-neighbour relationships between accident events, while the network **K function** evaluates spatial interaction across increasing network distances. Both functions were analysed together to provide complementary evidence of network-based spatial interaction.\n\n\n### 2.2.2 Network CSR and Monte Carlo Simulation\n\nNetwork-based CSR was used as the reference pattern. Under the null hypothesis, accident events are assumed to be randomly and independently distributed over the eligible Bangkok road network. Monte Carlo simulations were then used to generate reference envelopes for comparison with the observed G and K functions.\n\n::: {.callout-note title=\"Hypothesis\"}\n**H₀:** Road accidents are randomly and independently distributed along the Bangkok road network.\n\n**H₁:** Road accidents exhibit spatial interaction inconsistent with network CSR.\n:::\n\n::: {.callout-tip title=\"Parameter Selection\"}\nA 100 m width was adopted for the network G-function to provide a more stable representation of accident interaction across network-distance bands. Preliminary sensitivity checks indicated that the narrower 50 m width produced substantial short-range fluctuation.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\ngk_test <- kfunctions(\n  lines = roads_bkk_utm,\n  points = accident_snapped,\n  start = 0,\n  end = 1000,\n  step = 50,\n  width = 100,\n  nsim = 50,\n  resolution = 50,\n  verbose = TRUE,\n  conf_int = 0.05)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngk_test$plotk\n```\n\n::: {.cell-output-display}\n![](take-home_ex1_tr_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngk_test$plotg\n```\n\n::: {.cell-output-display}\n![](take-home_ex1_tr_files/figure-html/unnamed-chunk-51-2.png){width=672}\n:::\n\n```{.r .cell-code}\ngk_test$values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       obs_k   lower_k    upper_k distances    obs_g   lower_g   upper_g\n1    4380.60   0.00000    0.00000         0 18049.99  0.000000  79.93796\n2   18049.99   0.00000   79.93796        50 34948.88 31.975184 143.88833\n3   34948.88  31.97518  143.88833       100 24285.15 35.572392 172.26630\n4   42335.14  51.55998  207.83869       150 23485.77 31.975184 184.65669\n5   58434.65  99.52276  290.37464       200 22926.21 31.975184 159.87592\n6   65261.35 143.88833  319.75184       250 21103.62 15.987592 156.27871\n7   79538.27 147.48553  364.11740       300 20272.27  3.597208 140.29112\n8   85533.62 151.08274  412.08018       350 18465.67 15.987592 140.29112\n9   98003.94 183.05793  456.44575       400 18993.26 15.987592 127.90073\n10 104526.88 227.42349  488.42093       450 19936.53 15.987592 172.26630\n11 117940.47 259.39868  577.15207       500 19153.14 15.987592 159.87592\n12 123680.01 262.99589  633.90802       550 16978.82  3.597208 143.88833\n13 134919.29 303.76425  660.68723       600 17954.07 15.987592 124.30353\n14 141634.08 351.72702  705.05280       650 18465.67 31.975184 156.27871\n15 153384.96 367.71461  753.01558       700 18145.92 31.975184 156.27871\n16 159779.99 394.49383  816.96594       750 17362.52 19.584800 156.27871\n17 170747.48 426.46901  868.52593       800 16850.92 47.962776 143.88833\n18 176630.91 442.45660  911.29274       850 16307.34 23.182008 184.65669\n19 187054.82 510.00418  987.63349       900 17266.60 15.987592 159.87592\n20 193897.51 545.57657 1051.58385       950 16211.42 19.584800 172.26630\n21 203266.24 577.55176 1124.32740      1000 16579.13 35.572392 200.64428\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check whether observed functions exceed upper envelopes\nall(gk_test$values$obs_k[2:21] >\n      gk_test$values$upper_k[2:21])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nall(gk_test$values$obs_g[2:21] >\n      gk_test$values$upper_g[2:21])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### 2.2.3 Observed Functions and Simulation Envelopes\n\nThe observed K function remained above the upper Monte Carlo envelope across the examined network-distance scales, indicating stronger cumulative spatial clustering than expected under network-based CSR.\n\nSimilarly, the observed G function remained above the upper simulation envelope throughout the displayed distance bands. The strongest observed interaction occurred at short network distances, with the G-function reaching its highest value around 50 m before generally declining as distance increased.\n\nBoth functions provide consistent evidence against network-based CSR. The G function highlights strong short-range interaction between accident events, while the K function indicates that clustering persists cumulatively across broader network-distance scales.\n\n\n## 2.3 Overall Integration and Interpretation\n\nThe first and second order analyses provide complementary perspectives on the spatial pattern of road accidents in Bangkok. NKDE identifies where accident intensity is concentrated along the road network, while the network G  and K functions assess whether and at what spatial scales the observed accident pattern departs from network-based Complete Spatial Randomness.\n\nThe NKDE results reveal several concentrated and, in some locations, relatively continuous high-intensity road sections. When considered together with the network G and K function results, these concentrations form part of a broader non-random spatial pattern rather than appearing as isolated high-density locations.\n\nOverall, the combined analyses indicate that road accidents in Bangkok exhibit both localised network intensity and spatial interaction across multiple network-distance scales. However, these findings describe the spatial structure of accident occurrence rather than its underlying causes. Additional information on traffic exposure, road characteristics, and surrounding environmental conditions would be required to explain why particular road corridors experience higher accident intensity.\n\n\n# 3 Geovisualisation and Analytical Interpretation\n\n## 3.1 Temporal Animation Design\n\nTo complement the network-constrained spatial analyses, a temporal animation was developed to examine how the observed accident pattern accumulated throughout 2022.\n\nThe cleaned monthly attribute was used to organise accident events into twelve sequential states from January to December.\n\nA cumulative rather than month-by-month display was adopted so that accidents remain visible after their month of occurrence.\n\nThis allows the animation to show how the annual spatial pattern gradually emerges over time, while accident severity is retained to distinguish fatal, injury, and non-injury events.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_labels <- c(\n  \"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\",\n  \"Jul\", \"Aug\", \"Sept\", \"Oct\", \"Nov\", \"Dec\")\n\naccident_cumulative <- accident_snapped %>%\n  mutate(\n    month_num = match(as.character(month), month_labels)) %>%\n  tidyr::uncount(\n    weights = 13 - month_num,\n    .id = \"month_offset\") %>%\n  mutate(\n    display_month_num = month_num + month_offset - 1,\n    display_month = factor(\n      month_labels[display_month_num],\n      levels = month_labels,\n      ordered = TRUE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(\n    data = roads_bkk,\n    colour = \"grey80\",\n    linewidth = 0.2) +\n  geom_sf(\n    data = accident_cumulative %>%\n      filter(display_month == \"Dec\"),\n    aes(colour = severity),\n    size = 1,\n    alpha = 0.6) +\n  labs(\n    title = \"Road Traffic Accidents in Bangkok\",\n    subtitle = \"Cumulative accidents: January–December 2022\",\n    colour = \"Severity\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](take-home_ex1_tr_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n## 3.2 Animated Accident Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccident_animation <- ggplot() +\n  geom_sf(\n    data = roads_bkk,\n    colour = \"grey80\",\n    linewidth = 0.2) +\n  geom_sf(\n    data = accident_cumulative,\n    aes(colour = severity),\n    size = 1,\n    alpha = 0.6) +\n  transition_states(\n    display_month,\n    transition_length = 1,\n    state_length = 3) +\n  labs(\n    title = \"Cumulative Road Traffic Accidents in Bangkok — {closest_state} 2022\",\n    subtitle = \"Accidents accumulated from January to {closest_state}\",\n    colour = \"Severity\") +\n  theme_void() +\n  theme(\n    legend.position = \"right\")\n```\n:::\n\n\n\n\n![Bangkok Accident 2022](images/bangkok_accidents_2022.gif){width=80%}\n\nThe resulting animation displays the cumulative distribution of reported road accidents across the Bangkok road network from January to December 2022. Each successive frame incorporates newly recorded accidents while retaining events from previous months.\n\n## 3.3 Interpretation\n\nThe cumulative animation illustrates how the observed annual accident pattern progressively developed throughout 2022. As additional events are added over time, accident locations do not appear to accumulate uniformly across the entire road network. Instead, repeated concentrations become increasingly visible along particular parts of the network.\n\nBy the later months of the year, the cumulative distribution shows a clearer contrast between road sections with relatively dense accident occurrence and sections with comparatively few recorded events. Fatal, injury, and non-injury accidents are all represented within the evolving pattern, although the animation is intended primarily to visualize their spatial and temporal accumulation rather than to compare severity-specific rates.\n\nImportantly, the increasing number of visible points across successive frames is an inherent consequence of the cumulative design and should not be interpreted as evidence that accident risk increased over the course of the year. A month-specific temporal analysis would be required to evaluate seasonal changes or differences in accident frequency between months.\n\n## 3.4 Link to Network-Constrained Analysis\n\nThe temporal animation provides a descriptive time dimension to the spatial patterns identified in Section 2. While the animation shows how accident locations progressively accumulate across the network, NKDE summarizes the resulting spatial intensity along road segments and highlights locations with comparatively high accident concentration.\n\nThe network G and K functions address a different question by evaluating whether the spatial arrangement of accident events departs from network-based CSR and at what network-distance scales this interaction occurs. The animation should therefore be interpreted as complementary exploratory evidence rather than a statistical test of clustering.\n\nTogether, the three perspectives provide a more complete description of the observed accident pattern: the animation shows how the pattern develops over time, NKDE identifies where accident intensity is concentrated, and the network G and K functions assess whether and at what spatial scales the observed spatial arrangement differs from the network-based random reference.\n\n\n# 4 Public-Safety Planning and Management\n\n## 4.1 Road-Safety Prioritization\n\nThe NKDE results provide a network-based basis for prioritizing road sections for further road-safety investigation. Rather than allocating attention uniformly across Bangkok, planners can use high-intensity corridors as an initial screening layer for targeted investigation.\nImportantly, high NKDE intensity should not be interpreted directly as evidence of unsafe road design. Accident concentration may also reflect traffic exposure, road hierarchy, intersection density, land use, or other contextual factors that are not represented in the current dataset.\n\nThe identified high-intensity sections can therefore be treated as priority screening locations where more detailed investigation of road design, traffic conditions, intersection characteristics, and surrounding land use may be warranted.\n\n## 4.2 Operational and Strategic Planning Applications\n\nFrom an operational perspective, NKDE can support the identification of specific road sections for targeted investigation. These locations may be prioritized for further examination of traffic conditions, junction design, signage, lighting, pedestrian infrastructure, or other locally relevant factors.\n\nFrom a strategic perspective, the network G and K function results indicate that accident occurrence should not necessarily be considered as a collection of independent locations. The observed clustering across network-distance scales suggests that connected road corridors and surrounding network structure may also be relevant when defining broader road-safety study areas.\n\nThe temporal animation adds a monitoring perspective by demonstrating how the annual accident pattern develops as events accumulate. With data covering multiple years, a similar approach could be extended to examine whether identified concentrations persist, emerge, or shift over time.\n\n## 4.3 Limitations and Further Analysis\n\n1. **Traffic Exposure**\n\nTraffic volume and vehicle kilometres travelled are not considered. Therefore, NKDE represents **accident intensity rather than accident risk**.\n\n2. **Bandwidth Selection**\n\nNKDE results are sensitive to bandwidth selection. The 500 m bandwidth represents a selected analytical scale rather than an optimal value.\n\n3. **Road Network Representation**\n\nThe road network is derived from OpenStreetMap and filtered by road class. Differences in network completeness or classification may affect the results.\n\n4. **Network CSR Assumption**\n\nNetwork CSR assumes that accidents are equally likely to occur across the eligible road network. In reality, traffic exposure varies between road sections.\n\n5. **Temporal Coverage**\n\nOnly accident records from 2022 are analysed. The identified patterns may therefore be specific to that year rather than persistent over time.\n\n6. **Reporting and Positional Accuracy**\n\nIncomplete reporting or inaccurate coordinates may affect the observed pattern. Snapping improves network alignment but does not guarantee the exact accident location.\n\n7. **Accident Severity**\n\nAll accidents are treated equally regardless of severity. The results therefore represent overall accident concentration rather than the concentration of severe or fatal accidents.\n\n\n# 5 Executive Summary\n\n[Executive Summary Slide](https://isss-626-course.vercel.app/take-home_exercise/take-home_ex1_slide.html#/title-slide){target=\"_blank\"}\n\n\n# References\n\nGeofabrik GmbH. (n.d.). *OpenStreetMap data extracts*. \nhttps://download.geofabrik.de/\n\nOpenStreetMap contributors. (n.d.). *OpenStreetMap*. \nhttps://www.openstreetmap.org/\n\nRunfola, D., Anderson, A., Baier, H., Crittenden, M., Dowker, E., Fuhrig, S., \nGoodman, S., Grimsley, G., Layko, R., Melville, G., Mulder, M., Oberman, R., \nPanganiban, J., Peckham, S., Seitz, L., Shea, K., Slevin, H., Youngerman, R., \n& Hobbs, L. (2020). geoBoundaries: A global database of political \nadministrative boundaries. *PLOS ONE, 15*(4), e0231866. \nhttps://doi.org/10.1371/journal.pone.0231866\n\nOkabe, A., & Sugihara, K. (2012). *Spatial analysis along networks: \nStatistical and computational methods*. John Wiley & Sons.\n\n*R for Geospatial Data Science and Analytics: First-order spatial point patterns analysis methods*. (2026). https://r4gdsa.netlify.app/chap04\n\n*R for Geospatial Data Science and Analytics: Second-order spatial point patterns analysis methods*. (2026). https://r4gdsa.netlify.app/chap05\n\n*R for Geospatial Data Science and Analytics: Network-constrained spatial point patterns analysis*. (2026). https://r4gdsa.netlify.app/chap07\n\n\n# AI Tool Use Declaration\n\nGenerative AI tools were used as supporting tools for brainstorming, refining written expression, and improving the organisation and presentation of this report. \n\nAll analytical procedures, R code, methodological decisions, results, and interpretations were conducted, reviewed, and validated by the author. AI-generated suggestions were critically evaluated and revised where necessary before being incorporated into the report.\n\nAI tools were also consulted for troubleshooting selected R and Quarto implementation issues.\n\n\n# Appendix\n\n## Appendix A: Data Source Documentation\n\n\n::: {#tbl-data-sources .cell}\n::: {.cell-output-display}\n\n\nTable: Data sources used in the analysis.\n\n|Dataset                 |Source                                  |Geographic Coverage |Temporal Coverage            |Access Date       |Analytical Role                                       |\n|:-----------------------|:---------------------------------------|:-------------------|:----------------------------|:-----------------|:-----------------------------------------------------|\n|Road Accident Records   |Thailand Road Accident Dataset (Kaggle) |Thailand            |2019–2022 (2022 selected)    |12 September 2026 |Accident point events                                 |\n|Administrative Boundary |geoBoundaries (ADM1)                    |Thailand            |Not applicable               |21 September 2026 |Definition and clipping of Bangkok study area         |\n|Road Network            |OpenStreetMap via Geofabrik             |Thailand            |Snapshot at time of download |21 September 2026 |Road network for network-constrained spatial analysis |\n\n\n:::\n:::\n\n\n## Appendix B: Summary of Methodological Decisions\n\n\n::: {#tbl-methodological-decisions .cell}\n::: {.cell-output-display}\n\n\nTable: Summary of key methodological decisions and analytical settings.\n\n|Component              |Decision              |Selected Setting |Basis / Rationale                                                 |\n|:----------------------|:---------------------|:----------------|:-----------------------------------------------------------------|\n|Study Design           |Study period          |2022             |Defines a consistent one-year analytical window                   |\n|Study Design           |Study area            |Bangkok Province |Defines a consistent spatial extent for the analysis              |\n|Spatial Pre-processing |Projected CRS         |EPSG:32647       |Enables distance-based analysis in metres                         |\n|Network Preparation    |Snapping tolerance    |30 m             |Selected based on point-to-network distance validation            |\n|First-order Analysis   |NKDE bandwidth        |500 m            |Selected after bandwidth comparison                               |\n|First-order Analysis   |Kernel function       |Quartic          |Provides smooth distance-decaying density estimation              |\n|Second-order Analysis  |Distance range        |0–1,000 m        |Examines short- to intermediate-range network interaction         |\n|Second-order Analysis  |G-function width      |100 m            |Selected to improve stability relative to narrower distance bands |\n|CSR Simulation         |Number of simulations |50               |Used to construct Monte Carlo simulation envelopes                |\n|CSR Simulation         |Null model            |Network CSR      |Represents random event placement along the eligible road network |\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "take-home_ex1_tr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}